// Advanced Pack - 200 challenging keywords for experienced players
import { KeywordPair } from '../defaultKeywords';

export const ADVANCED_PACK_KEYWORDS: KeywordPair[] = [
  // ABSTRACT CONCEPTS (30 pairs)
  { civilian: 'Love', spy: 'Affection', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Fear', spy: 'Anxiety', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Joy', spy: 'Happiness', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Anger', spy: 'Rage', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Sadness', spy: 'Sorrow', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Pride', spy: 'Arrogance', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Jealousy', spy: 'Envy', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Hope', spy: 'Optimism', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Trust', spy: 'Faith', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Courage', spy: 'Bravery', category: 'Emotions', difficulty: 'hard' },
  { civilian: 'Democracy', spy: 'Republic', category: 'Politics', difficulty: 'hard' },
  { civilian: 'Freedom', spy: 'Liberty', category: 'Politics', difficulty: 'hard' },
  { civilian: 'Justice', spy: 'Fairness', category: 'Politics', difficulty: 'hard' },
  { civilian: 'Law', spy: 'Rule', category: 'Politics', difficulty: 'hard' },
  { civilian: 'Peace', spy: 'Harmony', category: 'Politics', difficulty: 'hard' },
  { civilian: 'War', spy: 'Conflict', category: 'Politics', difficulty: 'hard' },
  { civilian: 'Revolution', spy: 'Uprising', category: 'Politics', difficulty: 'hard' },
  { civilian: 'Capitalism', spy: 'Free Market', category: 'Economics', difficulty: 'hard' },
  { civilian: 'Socialism', spy: 'Communism', category: 'Economics', difficulty: 'hard' },
  { civilian: 'Poverty', spy: 'Destitution', category: 'Economics', difficulty: 'hard' },
  { civilian: 'Wealth', spy: 'Riches', category: 'Economics', difficulty: 'hard' },
  { civilian: 'Inflation', spy: 'Deflation', category: 'Economics', difficulty: 'hard' },
  { civilian: 'Profit', spy: 'Gain', category: 'Economics', difficulty: 'hard' },
  { civilian: 'Investment', spy: 'Speculation', category: 'Economics', difficulty: 'hard' },
  { civilian: 'Philosophy', spy: 'Wisdom', category: 'Abstract', difficulty: 'hard' },
  { civilian: 'Truth', spy: 'Fact', category: 'Abstract', difficulty: 'hard' },
  { civilian: 'Beauty', spy: 'Elegance', category: 'Abstract', difficulty: 'hard' },
  { civilian: 'Ethics', spy: 'Morality', category: 'Abstract', difficulty: 'hard' },
  { civilian: 'Reality', spy: 'Existence', category: 'Abstract', difficulty: 'hard' },
  { civilian: 'Time', spy: 'Duration', category: 'Abstract', difficulty: 'hard' },

  // PROFESSIONS (25 pairs)
  { civilian: 'Doctor', spy: 'Surgeon', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Lawyer', spy: 'Attorney', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Teacher', spy: 'Professor', category: 'Professions', difficulty: 'easy' },
  { civilian: 'Engineer', spy: 'Architect', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Chef', spy: 'Cook', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Artist', spy: 'Painter', category: 'Professions', difficulty: 'easy' },
  { civilian: 'Writer', spy: 'Author', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Journalist', spy: 'Reporter', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Photographer', spy: 'Cameraman', category: 'Professions', difficulty: 'easy' },
  { civilian: 'Pilot', spy: 'Captain', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Soldier', spy: 'Warrior', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Firefighter', spy: 'Paramedic', category: 'Professions', difficulty: 'easy' },
  { civilian: 'Police Officer', spy: 'Detective', category: 'Professions', difficulty: 'easy' },
  { civilian: 'Banker', spy: 'Accountant', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Manager', spy: 'Director', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Secretary', spy: 'Assistant', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Scientist', spy: 'Researcher', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Farmer', spy: 'Rancher', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Mechanic', spy: 'Technician', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Electrician', spy: 'Plumber', category: 'Professions', difficulty: 'easy' },
  { civilian: 'Barber', spy: 'Hairdresser', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Waiter', spy: 'Server', category: 'Professions', difficulty: 'hard' },
  { civilian: 'Cashier', spy: 'Clerk', category: 'Professions', difficulty: 'medium' },
  { civilian: 'Librarian', spy: 'Archivist', category: 'Professions', difficulty: 'hard' },
  { civilian: 'Therapist', spy: 'Counselor', category: 'Professions', difficulty: 'medium' },

  // BODY PARTS (20 pairs)
  { civilian: 'Heart', spy: 'Lung', category: 'Body', difficulty: 'easy' },
  { civilian: 'Brain', spy: 'Mind', category: 'Body', difficulty: 'hard' },
  { civilian: 'Liver', spy: 'Kidney', category: 'Body', difficulty: 'medium' },
  { civilian: 'Stomach', spy: 'Intestine', category: 'Body', difficulty: 'medium' },
  { civilian: 'Hand', spy: 'Foot', category: 'Body', difficulty: 'easy' },
  { civilian: 'Finger', spy: 'Toe', category: 'Body', difficulty: 'easy' },
  { civilian: 'Arm', spy: 'Leg', category: 'Body', difficulty: 'easy' },
  { civilian: 'Eye', spy: 'Ear', category: 'Body', difficulty: 'easy' },
  { civilian: 'Nose', spy: 'Mouth', category: 'Body', difficulty: 'easy' },
  { civilian: 'Tongue', spy: 'Teeth', category: 'Body', difficulty: 'easy' },
  { civilian: 'Hair', spy: 'Beard', category: 'Body', difficulty: 'easy' },
  { civilian: 'Skin', spy: 'Flesh', category: 'Body', difficulty: 'medium' },
  { civilian: 'Bone', spy: 'Muscle', category: 'Body', difficulty: 'easy' },
  { civilian: 'Blood', spy: 'Vein', category: 'Body', difficulty: 'medium' },
  { civilian: 'Spine', spy: 'Backbone', category: 'Body', difficulty: 'hard' },
  { civilian: 'Skull', spy: 'Head', category: 'Body', difficulty: 'medium' },
  { civilian: 'Shoulder', spy: 'Elbow', category: 'Body', difficulty: 'easy' },
  { civilian: 'Wrist', spy: 'Ankle', category: 'Body', difficulty: 'medium' },
  { civilian: 'Knee', spy: 'Hip', category: 'Body', difficulty: 'easy' },
  { civilian: 'Chest', spy: 'Back', category: 'Body', difficulty: 'easy' },

  // ACTIONS/VERBS (25 pairs)
  { civilian: 'Walk', spy: 'Run', category: 'Actions', difficulty: 'easy' },
  { civilian: 'Jump', spy: 'Leap', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Swim', spy: 'Dive', category: 'Actions', difficulty: 'easy' },
  { civilian: 'Fly', spy: 'Glide', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Eat', spy: 'Drink', category: 'Actions', difficulty: 'easy' },
  { civilian: 'Sleep', spy: 'Rest', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Think', spy: 'Ponder', category: 'Actions', difficulty: 'hard' },
  { civilian: 'Read', spy: 'Write', category: 'Actions', difficulty: 'easy' },
  { civilian: 'Speak', spy: 'Talk', category: 'Actions', difficulty: 'hard' },
  { civilian: 'Listen', spy: 'Hear', category: 'Actions', difficulty: 'hard' },
  { civilian: 'See', spy: 'Watch', category: 'Actions', difficulty: 'hard' },
  { civilian: 'Touch', spy: 'Feel', category: 'Actions', difficulty: 'hard' },
  { civilian: 'Smell', spy: 'Sniff', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Laugh', spy: 'Smile', category: 'Actions', difficulty: 'easy' },
  { civilian: 'Cry', spy: 'Weep', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Sing', spy: 'Hum', category: 'Actions', difficulty: 'easy' },
  { civilian: 'Dance', spy: 'Move', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Play', spy: 'Perform', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Work', spy: 'Labor', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Study', spy: 'Learn', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Teach', spy: 'Instruct', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Help', spy: 'Assist', category: 'Actions', difficulty: 'hard' },
  { civilian: 'Fight', spy: 'Battle', category: 'Actions', difficulty: 'medium' },
  { civilian: 'Love', spy: 'Adore', category: 'Actions', difficulty: 'hard' },
  { civilian: 'Hate', spy: 'Despise', category: 'Actions', difficulty: 'hard' },

  // PLACES/LOCATIONS (25 pairs)
  { civilian: 'Hospital', spy: 'Clinic', category: 'Places', difficulty: 'easy' },
  { civilian: 'School', spy: 'University', category: 'Places', difficulty: 'easy' },
  { civilian: 'Library', spy: 'Bookstore', category: 'Places', difficulty: 'medium' },
  { civilian: 'Museum', spy: 'Gallery', category: 'Places', difficulty: 'medium' },
  { civilian: 'Theater', spy: 'Cinema', category: 'Places', difficulty: 'easy' },
  { civilian: 'Restaurant', spy: 'Cafe', category: 'Places', difficulty: 'easy' },
  { civilian: 'Hotel', spy: 'Motel', category: 'Places', difficulty: 'easy' },
  { civilian: 'Mall', spy: 'Market', category: 'Places', difficulty: 'easy' },
  { civilian: 'Park', spy: 'Garden', category: 'Places', difficulty: 'easy' },
  { civilian: 'Beach', spy: 'Shore', category: 'Places', difficulty: 'medium' },
  { civilian: 'Airport', spy: 'Station', category: 'Places', difficulty: 'easy' },
  { civilian: 'Bank', spy: 'ATM', category: 'Places', difficulty: 'easy' },
  { civilian: 'Church', spy: 'Temple', category: 'Places', difficulty: 'medium' },
  { civilian: 'Stadium', spy: 'Arena', category: 'Places', difficulty: 'medium' },
  { civilian: 'Office', spy: 'Workplace', category: 'Places', difficulty: 'medium' },
  { civilian: 'Factory', spy: 'Plant', category: 'Places', difficulty: 'medium' },
  { civilian: 'Farm', spy: 'Ranch', category: 'Places', difficulty: 'medium' },
  { civilian: 'Store', spy: 'Shop', category: 'Places', difficulty: 'hard' },
  { civilian: 'Bakery', spy: 'Deli', category: 'Places', difficulty: 'easy' },
  { civilian: 'Pharmacy', spy: 'Drugstore', category: 'Places', difficulty: 'hard' },
  { civilian: 'Gym', spy: 'Fitness Center', category: 'Places', difficulty: 'medium' },
  { civilian: 'Spa', spy: 'Salon', category: 'Places', difficulty: 'medium' },
  { civilian: 'Prison', spy: 'Jail', category: 'Places', difficulty: 'hard' },
  { civilian: 'Court', spy: 'Tribunal', category: 'Places', difficulty: 'hard' },
  { civilian: 'Embassy', spy: 'Consulate', category: 'Places', difficulty: 'hard' },

  // CLOTHING & ACCESSORIES (25 pairs)
  { civilian: 'Shirt', spy: 'Blouse', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Pants', spy: 'Trousers', category: 'Clothing', difficulty: 'hard' },
  { civilian: 'Dress', spy: 'Skirt', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Jacket', spy: 'Coat', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Sweater', spy: 'Cardigan', category: 'Clothing', difficulty: 'medium' },
  { civilian: 'Suit', spy: 'Tuxedo', category: 'Clothing', difficulty: 'medium' },
  { civilian: 'Jeans', spy: 'Denim', category: 'Clothing', difficulty: 'hard' },
  { civilian: 'Shorts', spy: 'Trunks', category: 'Clothing', difficulty: 'medium' },
  { civilian: 'Hat', spy: 'Cap', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Scarf', spy: 'Shawl', category: 'Clothing', difficulty: 'medium' },
  { civilian: 'Gloves', spy: 'Mittens', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Socks', spy: 'Stockings', category: 'Clothing', difficulty: 'medium' },
  { civilian: 'Shoes', spy: 'Boots', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Sneakers', spy: 'Trainers', category: 'Clothing', difficulty: 'hard' },
  { civilian: 'Sandals', spy: 'Flip-flops', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Belt', spy: 'Buckle', category: 'Clothing', difficulty: 'medium' },
  { civilian: 'Tie', spy: 'Bow Tie', category: 'Clothing', difficulty: 'easy' },
  { civilian: 'Watch', spy: 'Bracelet', category: 'Accessories', difficulty: 'easy' },
  { civilian: 'Necklace', spy: 'Chain', category: 'Accessories', difficulty: 'medium' },
  { civilian: 'Ring', spy: 'Earring', category: 'Accessories', difficulty: 'easy' },
  { civilian: 'Glasses', spy: 'Sunglasses', category: 'Accessories', difficulty: 'easy' },
  { civilian: 'Wallet', spy: 'Purse', category: 'Accessories', difficulty: 'easy' },
  { civilian: 'Backpack', spy: 'Suitcase', category: 'Accessories', difficulty: 'easy' },
  { civilian: 'Handbag', spy: 'Clutch', category: 'Accessories', difficulty: 'medium' },
  { civilian: 'Briefcase', spy: 'Portfolio', category: 'Accessories', difficulty: 'hard' },

  // ADJECTIVES (25 pairs)
  { civilian: 'Big', spy: 'Large', category: 'Adjectives', difficulty: 'hard' },
  { civilian: 'Small', spy: 'Tiny', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Hot', spy: 'Warm', category: 'Adjectives', difficulty: 'easy' },
  { civilian: 'Cold', spy: 'Cool', category: 'Adjectives', difficulty: 'easy' },
  { civilian: 'Fast', spy: 'Quick', category: 'Adjectives', difficulty: 'hard' },
  { civilian: 'Slow', spy: 'Gradual', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Strong', spy: 'Powerful', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Weak', spy: 'Feeble', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Heavy', spy: 'Weighty', category: 'Adjectives', difficulty: 'hard' },
  { civilian: 'Light', spy: 'Airy', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Tall', spy: 'High', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Short', spy: 'Brief', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Wide', spy: 'Broad', category: 'Adjectives', difficulty: 'hard' },
  { civilian: 'Narrow', spy: 'Thin', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Deep', spy: 'Profound', category: 'Adjectives', difficulty: 'hard' },
  { civilian: 'Shallow', spy: 'Superficial', category: 'Adjectives', difficulty: 'hard' },
  { civilian: 'Bright', spy: 'Brilliant', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Dark', spy: 'Dim', category: 'Adjectives', difficulty: 'easy' },
  { civilian: 'Loud', spy: 'Noisy', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Quiet', spy: 'Silent', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Soft', spy: 'Gentle', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Hard', spy: 'Solid', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Smooth', spy: 'Sleek', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Rough', spy: 'Coarse', category: 'Adjectives', difficulty: 'medium' },
  { civilian: 'Clean', spy: 'Pure', category: 'Adjectives', difficulty: 'medium' },

  // MATERIALS (25 pairs)
  { civilian: 'Wood', spy: 'Timber', category: 'Materials', difficulty: 'hard' },
  { civilian: 'Metal', spy: 'Steel', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Glass', spy: 'Crystal', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Plastic', spy: 'Polymer', category: 'Materials', difficulty: 'hard' },
  { civilian: 'Paper', spy: 'Cardboard', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Fabric', spy: 'Cloth', category: 'Materials', difficulty: 'hard' },
  { civilian: 'Leather', spy: 'Hide', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Cotton', spy: 'Linen', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Silk', spy: 'Satin', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Wool', spy: 'Fleece', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Stone', spy: 'Rock', category: 'Materials', difficulty: 'hard' },
  { civilian: 'Brick', spy: 'Cement', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Concrete', spy: 'Asphalt', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Sand', spy: 'Gravel', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Clay', spy: 'Mud', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Gold', spy: 'Silver', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Bronze', spy: 'Copper', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Iron', spy: 'Aluminum', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Diamond', spy: 'Ruby', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Pearl', spy: 'Jade', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Oil', spy: 'Gas', category: 'Materials', difficulty: 'easy' },
  { civilian: 'Coal', spy: 'Charcoal', category: 'Materials', difficulty: 'medium' },
  { civilian: 'Rubber', spy: 'Latex', category: 'Materials', difficulty: 'hard' },
  { civilian: 'Wax', spy: 'Resin', category: 'Materials', difficulty: 'hard' },
  { civilian: 'Ice', spy: 'Snow', category: 'Materials', difficulty: 'easy' },
];
