// Culture & History Pack - 250 keywords about history, landmarks, and cultural terms
import { KeywordPair } from '../defaultKeywords';

export const CULTURE_PACK_KEYWORDS: KeywordPair[] = [
  // HISTORICAL FIGURES (50 pairs)
  { civilian: 'Napoleon', spy: 'Caesar', category: 'Historical Figures', difficulty: 'medium' },
  { civilian: 'Einstein', spy: 'Newton', category: 'Scientists', difficulty: 'easy' },
  { civilian: 'Shakespeare', spy: 'Dante', category: 'Writers', difficulty: 'medium' },
  { civilian: 'Mozart', spy: 'Beethoven', category: 'Composers', difficulty: 'easy' },
  { civilian: 'Da Vinci', spy: 'Michelangelo', category: 'Artists', difficulty: 'easy' },
  { civilian: 'Cleopatra', spy: 'Nefertiti', category: 'Historical Figures', difficulty: 'medium' },
  { civilian: 'Lincoln', spy: 'Washington', category: 'Presidents', difficulty: 'easy' },
  { civilian: 'Gandhi', spy: 'Mandela', category: 'Leaders', difficulty: 'easy' },
  { civilian: 'Martin Luther King', spy: 'Malcolm X', category: 'Activists', difficulty: 'medium' },
  { civilian: 'Columbus', spy: 'Magellan', category: 'Explorers', difficulty: 'medium' },
  { civilian: 'Darwin', spy: 'Mendel', category: 'Scientists', difficulty: 'hard' },
  { civilian: 'Galileo', spy: 'Copernicus', category: 'Astronomers', difficulty: 'medium' },
  { civilian: 'Alexander the Great', spy: 'Genghis Khan', category: 'Conquerors', difficulty: 'medium' },
  { civilian: 'Confucius', spy: 'Buddha', category: 'Philosophers', difficulty: 'medium' },
  { civilian: 'Socrates', spy: 'Plato', category: 'Philosophers', difficulty: 'medium' },
  { civilian: 'Tesla', spy: 'Edison', category: 'Inventors', difficulty: 'easy' },
  { civilian: 'Marie Curie', spy: 'Rosalind Franklin', category: 'Scientists', difficulty: 'hard' },
  { civilian: 'Queen Elizabeth', spy: 'Queen Victoria', category: 'Royalty', difficulty: 'medium' },
  { civilian: 'Joan of Arc', spy: 'Florence Nightingale', category: 'Historical Women', difficulty: 'hard' },
  { civilian: 'Churchill', spy: 'Roosevelt', category: 'Leaders', difficulty: 'medium' },
  { civilian: 'Stalin', spy: 'Hitler', category: 'Dictators', difficulty: 'easy' },
  { civilian: 'Mao', spy: 'Lenin', category: 'Leaders', difficulty: 'medium' },
  { civilian: 'Marco Polo', spy: 'Ibn Battuta', category: 'Explorers', difficulty: 'hard' },
  { civilian: 'Spartacus', spy: 'Hannibal', category: 'Warriors', difficulty: 'medium' },
  { civilian: 'King Arthur', spy: 'Charlemagne', category: 'Legends', difficulty: 'medium' },
  { civilian: 'Homer', spy: 'Virgil', category: 'Ancient Writers', difficulty: 'hard' },
  { civilian: 'Picasso', spy: 'Van Gogh', category: 'Painters', difficulty: 'easy' },
  { civilian: 'Rembrandt', spy: 'Caravaggio', category: 'Painters', difficulty: 'hard' },
  { civilian: 'Bach', spy: 'Handel', category: 'Composers', difficulty: 'medium' },
  { civilian: 'Chopin', spy: 'Liszt', category: 'Composers', difficulty: 'hard' },
  { civilian: 'Tolstoy', spy: 'Dostoevsky', category: 'Russian Writers', difficulty: 'medium' },
  { civilian: 'Dickens', spy: 'Austen', category: 'British Writers', difficulty: 'medium' },
  { civilian: 'Mark Twain', spy: 'Edgar Allan Poe', category: 'American Writers', difficulty: 'medium' },
  { civilian: 'Aristotle', spy: 'Archimedes', category: 'Greek Thinkers', difficulty: 'medium' },
  { civilian: 'Julius Caesar', spy: 'Augustus', category: 'Roman Emperors', difficulty: 'medium' },
  { civilian: 'Ramses', spy: 'Tutankhamun', category: 'Pharaohs', difficulty: 'medium' },
  { civilian: 'Samurai', spy: 'Ninja', category: 'Japanese Warriors', difficulty: 'easy' },
  { civilian: 'Shogun', spy: 'Emperor', category: 'Japanese Rulers', difficulty: 'hard' },
  { civilian: 'Viking', spy: 'Barbarian', category: 'Warriors', difficulty: 'easy' },
  { civilian: 'Gladiator', spy: 'Soldier', category: 'Fighters', difficulty: 'easy' },
  { civilian: 'Knight', spy: 'Crusader', category: 'Medieval Warriors', difficulty: 'medium' },
  { civilian: 'Pharaoh', spy: 'Sultan', category: 'Rulers', difficulty: 'medium' },
  { civilian: 'Emperor', spy: 'King', category: 'Royalty', difficulty: 'easy' },
  { civilian: 'Prince', spy: 'Duke', category: 'Nobility', difficulty: 'medium' },
  { civilian: 'Monk', spy: 'Priest', category: 'Religious', difficulty: 'easy' },
  { civilian: 'Prophet', spy: 'Messiah', category: 'Religious', difficulty: 'hard' },
  { civilian: 'Saint', spy: 'Martyr', category: 'Religious', difficulty: 'medium' },
  { civilian: 'Pope', spy: 'Cardinal', category: 'Catholic', difficulty: 'easy' },
  { civilian: 'Rabbi', spy: 'Imam', category: 'Religious Leaders', difficulty: 'medium' },
  { civilian: 'Shaman', spy: 'Druid', category: 'Spiritual', difficulty: 'hard' },

  // LANDMARKS & MONUMENTS (50 pairs)
  { civilian: 'Eiffel Tower', spy: 'Statue of Liberty', category: 'Monuments', difficulty: 'easy' },
  { civilian: 'Pyramids', spy: 'Sphinx', category: 'Egyptian', difficulty: 'easy' },
  { civilian: 'Great Wall', spy: 'Forbidden City', category: 'Chinese', difficulty: 'medium' },
  { civilian: 'Colosseum', spy: 'Pantheon', category: 'Roman', difficulty: 'medium' },
  { civilian: 'Taj Mahal', spy: 'Red Fort', category: 'Indian', difficulty: 'medium' },
  { civilian: 'Big Ben', spy: 'London Eye', category: 'British', difficulty: 'easy' },
  { civilian: 'Mount Rushmore', spy: 'Lincoln Memorial', category: 'American', difficulty: 'medium' },
  { civilian: 'Acropolis', spy: 'Parthenon', category: 'Greek', difficulty: 'medium' },
  { civilian: 'Machu Picchu', spy: 'Chichen Itza', category: 'Ancient Americas', difficulty: 'medium' },
  { civilian: 'Stonehenge', spy: 'Easter Island', category: 'Mysterious', difficulty: 'medium' },
  { civilian: 'Burj Khalifa', spy: 'Empire State', category: 'Skyscrapers', difficulty: 'easy' },
  { civilian: 'Sydney Opera', spy: 'Royal Albert Hall', category: 'Concert Halls', difficulty: 'medium' },
  { civilian: 'Louvre', spy: 'Vatican', category: 'Museums', difficulty: 'easy' },
  { civilian: 'Notre Dame', spy: 'Westminster Abbey', category: 'Cathedrals', difficulty: 'medium' },
  { civilian: 'Buckingham Palace', spy: 'Versailles', category: 'Palaces', difficulty: 'medium' },
  { civilian: 'White House', spy: 'Capitol', category: 'US Government', difficulty: 'easy' },
  { civilian: 'Kremlin', spy: 'Red Square', category: 'Russian', difficulty: 'medium' },
  { civilian: 'Golden Gate', spy: 'Brooklyn Bridge', category: 'Bridges', difficulty: 'easy' },
  { civilian: 'Angkor Wat', spy: 'Borobudur', category: 'Asian Temples', difficulty: 'hard' },
  { civilian: 'Petra', spy: 'Palmyra', category: 'Ancient Cities', difficulty: 'hard' },
  { civilian: 'Sagrada Familia', spy: 'Arc de Triomphe', category: 'Architecture', difficulty: 'medium' },
  { civilian: 'St. Basil', spy: 'Blue Mosque', category: 'Religious Buildings', difficulty: 'medium' },
  { civilian: 'Brandenburg Gate', spy: 'Reichstag', category: 'German', difficulty: 'hard' },
  { civilian: 'CN Tower', spy: 'Space Needle', category: 'Towers', difficulty: 'medium' },
  { civilian: 'Alhambra', spy: 'Alcazar', category: 'Spanish', difficulty: 'hard' },
  { civilian: 'Neuschwanstein', spy: 'Edinburgh Castle', category: 'Castles', difficulty: 'hard' },
  { civilian: 'Vatican City', spy: 'Monaco', category: 'City-States', difficulty: 'medium' },
  { civilian: 'Times Square', spy: 'Piccadilly Circus', category: 'City Centers', difficulty: 'medium' },
  { civilian: 'Wall Street', spy: 'Dow Jones', category: 'Finance', difficulty: 'medium' },
  { civilian: 'Hollywood', spy: 'Bollywood', category: 'Film Industry', difficulty: 'easy' },
  { civilian: 'Broadway', spy: 'West End', category: 'Theater Districts', difficulty: 'medium' },
  { civilian: 'Silicon Valley', spy: 'Route 128', category: 'Tech Hubs', difficulty: 'hard' },
  { civilian: 'Pentagon', spy: 'Cheyenne Mountain', category: 'Military', difficulty: 'medium' },
  { civilian: 'Area 51', spy: 'Roswell', category: 'Mysterious Places', difficulty: 'easy' },
  { civilian: 'Bermuda Triangle', spy: 'Devil\'s Sea', category: 'Mysterious', difficulty: 'medium' },
  { civilian: 'Mount Everest', spy: 'K2', category: 'Mountains', difficulty: 'easy' },
  { civilian: 'Grand Canyon', spy: 'Victoria Falls', category: 'Natural Wonders', difficulty: 'easy' },
  { civilian: 'Niagara Falls', spy: 'Iguazu Falls', category: 'Waterfalls', difficulty: 'medium' },
  { civilian: 'Dead Sea', spy: 'Great Salt Lake', category: 'Salt Lakes', difficulty: 'hard' },
  { civilian: 'Amazon', spy: 'Congo', category: 'Rainforests', difficulty: 'medium' },
  { civilian: 'Sahara', spy: 'Gobi', category: 'Deserts', difficulty: 'easy' },
  { civilian: 'Antarctica', spy: 'Arctic', category: 'Polar Regions', difficulty: 'medium' },
  { civilian: 'Hawaii', spy: 'Tahiti', category: 'Islands', difficulty: 'easy' },
  { civilian: 'Caribbean', spy: 'Mediterranean', category: 'Seas', difficulty: 'easy' },
  { civilian: 'Atlantic', spy: 'Pacific', category: 'Oceans', difficulty: 'easy' },
  { civilian: 'Europe', spy: 'Asia', category: 'Continents', difficulty: 'easy' },
  { civilian: 'North Pole', spy: 'South Pole', category: 'Extremes', difficulty: 'easy' },
  { civilian: 'Equator', spy: 'Prime Meridian', category: 'Geography', difficulty: 'hard' },
  { civilian: 'Tropic of Cancer', spy: 'Arctic Circle', category: 'Lines', difficulty: 'hard' },
  { civilian: 'Greenwich', spy: 'International Date Line', category: 'Time Zones', difficulty: 'hard' },

  // HISTORICAL EVENTS & PERIODS (50 pairs)
  { civilian: 'Renaissance', spy: 'Enlightenment', category: 'Periods', difficulty: 'medium' },
  { civilian: 'Industrial Revolution', spy: 'Agricultural Revolution', category: 'Revolutions', difficulty: 'medium' },
  { civilian: 'World War I', spy: 'World War II', category: 'Wars', difficulty: 'easy' },
  { civilian: 'Cold War', spy: 'Space Race', category: '20th Century', difficulty: 'medium' },
  { civilian: 'French Revolution', spy: 'American Revolution', category: 'Revolutions', difficulty: 'easy' },
  { civilian: 'Roman Empire', spy: 'Byzantine Empire', category: 'Empires', difficulty: 'medium' },
  { civilian: 'Ottoman Empire', spy: 'Mongol Empire', category: 'Empires', difficulty: 'medium' },
  { civilian: 'Middle Ages', spy: 'Dark Ages', category: 'Periods', difficulty: 'medium' },
  { civilian: 'Stone Age', spy: 'Bronze Age', category: 'Ancient Periods', difficulty: 'easy' },
  { civilian: 'Ice Age', spy: 'Jurassic Period', category: 'Prehistoric', difficulty: 'easy' },
  { civilian: 'Classical Period', spy: 'Hellenistic Period', category: 'Ancient Greece', difficulty: 'hard' },
  { civilian: 'Victorian Era', spy: 'Edwardian Era', category: 'British Periods', difficulty: 'hard' },
  { civilian: 'Great Depression', spy: 'Recession', category: 'Economic', difficulty: 'medium' },
  { civilian: 'Civil War', spy: 'Revolutionary War', category: 'American Wars', difficulty: 'easy' },
  { civilian: 'Holocaust', spy: 'Genocide', category: 'Tragedies', difficulty: 'medium' },
  { civilian: 'Pearl Harbor', spy: 'Hiroshima', category: 'WW2 Events', difficulty: 'easy' },
  { civilian: 'D-Day', spy: 'V-E Day', category: 'WW2 Events', difficulty: 'medium' },
  { civilian: 'Fall of Rome', spy: 'Fall of Constantinople', category: 'Historical Falls', difficulty: 'hard' },
  { civilian: 'Crusades', spy: 'Jihad', category: 'Religious Wars', difficulty: 'medium' },
  { civilian: 'Reformation', spy: 'Counter-Reformation', category: 'Religious Movements', difficulty: 'hard' },
  { civilian: 'Magna Carta', spy: 'Bill of Rights', category: 'Documents', difficulty: 'medium' },
  { civilian: 'Declaration', spy: 'Constitution', category: 'US Documents', difficulty: 'medium' },
  { civilian: 'Treaty of Versailles', spy: 'Treaty of Paris', category: 'Treaties', difficulty: 'hard' },
  { civilian: 'Black Death', spy: 'Spanish Flu', category: 'Pandemics', difficulty: 'medium' },
  { civilian: 'Salem Trials', spy: 'Inquisition', category: 'Witch Hunts', difficulty: 'medium' },
  { civilian: 'Gold Rush', spy: 'Oil Boom', category: 'Economic Events', difficulty: 'medium' },
  { civilian: 'Space Race', spy: 'Arms Race', category: 'Cold War', difficulty: 'medium' },
  { civilian: 'Moon Landing', spy: 'Mars Rover', category: 'Space Exploration', difficulty: 'easy' },
  { civilian: 'Berlin Wall', spy: 'Iron Curtain', category: 'Cold War Symbols', difficulty: 'easy' },
  { civilian: 'Communism', spy: 'Fascism', category: 'Ideologies', difficulty: 'medium' },
  { civilian: 'Monarchy', spy: 'Dictatorship', category: 'Government Types', difficulty: 'easy' },
  { civilian: 'Colony', spy: 'Territory', category: 'Political', difficulty: 'medium' },
  { civilian: 'Independence', spy: 'Liberation', category: 'Political Events', difficulty: 'hard' },
  { civilian: 'Coup', spy: 'Rebellion', category: 'Uprisings', difficulty: 'medium' },
  { civilian: 'Exile', spy: 'Banishment', category: 'Punishment', difficulty: 'hard' },
  { civilian: 'Assassination', spy: 'Execution', category: 'Death', difficulty: 'easy' },
  { civilian: 'Slavery', spy: 'Serfdom', category: 'Labor Systems', difficulty: 'medium' },
  { civilian: 'Emancipation', spy: 'Abolition', category: 'Freedom Movements', difficulty: 'hard' },
  { civilian: 'Suffrage', spy: 'Voting Rights', category: 'Rights', difficulty: 'hard' },
  { civilian: 'Prohibition', spy: 'Temperance', category: 'Social Movements', difficulty: 'medium' },
  { civilian: 'Civil Rights', spy: 'Human Rights', category: 'Movements', difficulty: 'medium' },
  { civilian: 'Feminism', spy: 'Equality', category: 'Social Justice', difficulty: 'medium' },
  { civilian: 'Imperialism', spy: 'Colonialism', category: 'Political Systems', difficulty: 'hard' },
  { civilian: 'Nationalism', spy: 'Patriotism', category: 'Ideologies', difficulty: 'hard' },
  { civilian: 'Propaganda', spy: 'Censorship', category: 'Control', difficulty: 'medium' },
  { civilian: 'Summit', spy: 'Conference', category: 'Diplomacy', difficulty: 'hard' },
  { civilian: 'Alliance', spy: 'Treaty', category: 'Agreements', difficulty: 'medium' },
  { civilian: 'Annexation', spy: 'Occupation', category: 'Conquest', difficulty: 'hard' },
  { civilian: 'Partition', spy: 'Division', category: 'Separation', difficulty: 'hard' },
  { civilian: 'Unification', spy: 'Consolidation', category: 'Joining', difficulty: 'hard' },

  // CULTURAL ELEMENTS (50 pairs)
  { civilian: 'Ballet', spy: 'Opera', category: 'Performing Arts', difficulty: 'easy' },
  { civilian: 'Symphony', spy: 'Concerto', category: 'Classical Music', difficulty: 'medium' },
  { civilian: 'Jazz', spy: 'Blues', category: 'Music Genres', difficulty: 'easy' },
  { civilian: 'Rock', spy: 'Pop', category: 'Music Genres', difficulty: 'easy' },
  { civilian: 'Hip Hop', spy: 'Rap', category: 'Music Genres', difficulty: 'hard' },
  { civilian: 'Folk Music', spy: 'Country Music', category: 'Traditional', difficulty: 'easy' },
  { civilian: 'Tango', spy: 'Salsa', category: 'Dances', difficulty: 'easy' },
  { civilian: 'Waltz', spy: 'Foxtrot', category: 'Ballroom', difficulty: 'medium' },
  { civilian: 'Tragedy', spy: 'Comedy', category: 'Drama', difficulty: 'easy' },
  { civilian: 'Epic', spy: 'Saga', category: 'Literature', difficulty: 'medium' },
  { civilian: 'Novel', spy: 'Novella', category: 'Literature', difficulty: 'medium' },
  { civilian: 'Poetry', spy: 'Prose', category: 'Writing', difficulty: 'easy' },
  { civilian: 'Haiku', spy: 'Sonnet', category: 'Poem Forms', difficulty: 'medium' },
  { civilian: 'Mythology', spy: 'Folklore', category: 'Stories', difficulty: 'medium' },
  { civilian: 'Legend', spy: 'Myth', category: 'Tales', difficulty: 'hard' },
  { civilian: 'Fable', spy: 'Parable', category: 'Moral Stories', difficulty: 'hard' },
  { civilian: 'Anime', spy: 'Manga', category: 'Japanese Media', difficulty: 'easy' },
  { civilian: 'Kimono', spy: 'Yukata', category: 'Japanese Clothing', difficulty: 'hard' },
  { civilian: 'Sushi', spy: 'Sashimi', category: 'Japanese Food', difficulty: 'medium' },
  { civilian: 'Sake', spy: 'Shochu', category: 'Japanese Drinks', difficulty: 'hard' },
  { civilian: 'Karate', spy: 'Judo', category: 'Martial Arts', difficulty: 'easy' },
  { civilian: 'Kung Fu', spy: 'Tai Chi', category: 'Chinese Martial Arts', difficulty: 'medium' },
  { civilian: 'Yoga', spy: 'Meditation', category: 'Spiritual Practice', difficulty: 'easy' },
  { civilian: 'Hinduism', spy: 'Buddhism', category: 'Religions', difficulty: 'easy' },
  { civilian: 'Christianity', spy: 'Islam', category: 'Religions', difficulty: 'easy' },
  { civilian: 'Judaism', spy: 'Zoroastrianism', category: 'Religions', difficulty: 'medium' },
  { civilian: 'Catholic', spy: 'Protestant', category: 'Christianity', difficulty: 'easy' },
  { civilian: 'Orthodox', spy: 'Anglican', category: 'Christianity', difficulty: 'hard' },
  { civilian: 'Sunni', spy: 'Shia', category: 'Islam', difficulty: 'medium' },
  { civilian: 'Reincarnation', spy: 'Resurrection', category: 'Afterlife', difficulty: 'hard' },
  { civilian: 'Heaven', spy: 'Paradise', category: 'Afterlife', difficulty: 'medium' },
  { civilian: 'Hell', spy: 'Purgatory', category: 'Afterlife', difficulty: 'medium' },
  { civilian: 'Angel', spy: 'Demon', category: 'Spiritual Beings', difficulty: 'easy' },
  { civilian: 'God', spy: 'Deity', category: 'Divine', difficulty: 'hard' },
  { civilian: 'Ritual', spy: 'Ceremony', category: 'Religious Practice', difficulty: 'hard' },
  { civilian: 'Pilgrimage', spy: 'Crusade', category: 'Religious Journey', difficulty: 'medium' },
  { civilian: 'Baptism', spy: 'Confirmation', category: 'Sacraments', difficulty: 'medium' },
  { civilian: 'Wedding', spy: 'Marriage', category: 'Ceremonies', difficulty: 'hard' },
  { civilian: 'Funeral', spy: 'Memorial', category: 'Death Rituals', difficulty: 'medium' },
  { civilian: 'Festival', spy: 'Celebration', category: 'Events', difficulty: 'medium' },
  { civilian: 'Carnival', spy: 'Mardi Gras', category: 'Festivals', difficulty: 'medium' },
  { civilian: 'Christmas', spy: 'Easter', category: 'Christian Holidays', difficulty: 'easy' },
  { civilian: 'Hanukkah', spy: 'Passover', category: 'Jewish Holidays', difficulty: 'easy' },
  { civilian: 'Ramadan', spy: 'Eid', category: 'Islamic Holidays', difficulty: 'easy' },
  { civilian: 'Diwali', spy: 'Holi', category: 'Hindu Festivals', difficulty: 'medium' },
  { civilian: 'Lunar New Year', spy: 'Dragon Boat Festival', category: 'Chinese Festivals', difficulty: 'medium' },
  { civilian: 'Thanksgiving', spy: 'Independence Day', category: 'American Holidays', difficulty: 'easy' },
  { civilian: 'Halloween', spy: 'Day of the Dead', category: 'Autumn Festivals', difficulty: 'easy' },
  { civilian: 'New Year', spy: 'New Year\'s Eve', category: 'Celebrations', difficulty: 'hard' },
  { civilian: 'Birthday', spy: 'Anniversary', category: 'Personal Celebrations', difficulty: 'easy' },

  // WORLD CIVILIZATIONS (50 pairs)
  { civilian: 'Ancient Egypt', spy: 'Ancient Greece', category: 'Civilizations', difficulty: 'easy' },
  { civilian: 'Ancient Rome', spy: 'Carthage', category: 'Mediterranean', difficulty: 'medium' },
  { civilian: 'Maya', spy: 'Aztec', category: 'Mesoamerican', difficulty: 'easy' },
  { civilian: 'Inca', spy: 'Olmec', category: 'South American', difficulty: 'medium' },
  { civilian: 'Mesopotamia', spy: 'Babylonia', category: 'Ancient Near East', difficulty: 'medium' },
  { civilian: 'Persia', spy: 'Arabia', category: 'Middle Eastern', difficulty: 'medium' },
  { civilian: 'Han Dynasty', spy: 'Tang Dynasty', category: 'Chinese Dynasties', difficulty: 'hard' },
  { civilian: 'Qing Dynasty', spy: 'Ming Dynasty', category: 'Chinese Dynasties', difficulty: 'hard' },
  { civilian: 'Edo Period', spy: 'Meiji Era', category: 'Japanese Periods', difficulty: 'hard' },
  { civilian: 'Samurai Era', spy: 'Shogunate', category: 'Japanese History', difficulty: 'medium' },
  { civilian: 'Viking Age', spy: 'Medieval Scandinavia', category: 'Norse', difficulty: 'medium' },
  { civilian: 'Celtic', spy: 'Gaelic', category: 'European Tribes', difficulty: 'hard' },
  { civilian: 'Germanic Tribes', spy: 'Gothic Tribes', category: 'Barbarians', difficulty: 'hard' },
  { civilian: 'Phoenicians', spy: 'Minoans', category: 'Maritime', difficulty: 'hard' },
  { civilian: 'Sparta', spy: 'Athens', category: 'Greek City-States', difficulty: 'easy' },
  { civilian: 'Troy', spy: 'Mycenae', category: 'Ancient Greek', difficulty: 'hard' },
  { civilian: 'Etruscans', spy: 'Samnites', category: 'Pre-Roman Italy', difficulty: 'hard' },
  { civilian: 'Gaul', spy: 'Germania', category: 'Roman Territories', difficulty: 'hard' },
  { civilian: 'Britannia', spy: 'Hispania', category: 'Roman Provinces', difficulty: 'hard' },
  { civilian: 'East Roman', spy: 'West Roman', category: 'Roman Division', difficulty: 'medium' },
  { civilian: 'Franks', spy: 'Saxons', category: 'Germanic Peoples', difficulty: 'hard' },
  { civilian: 'Normans', spy: 'Anglo-Saxons', category: 'Medieval British', difficulty: 'hard' },
  { civilian: 'Crusader States', spy: 'Latin Kingdoms', category: 'Medieval Near East', difficulty: 'hard' },
  { civilian: 'Holy Roman Empire', spy: 'Habsburg Empire', category: 'European Empires', difficulty: 'hard' },
  { civilian: 'Prussian', spy: 'Austrian', category: 'Germanic States', difficulty: 'hard' },
  { civilian: 'British Empire', spy: 'French Empire', category: 'Colonial Empires', difficulty: 'easy' },
  { civilian: 'Spanish Empire', spy: 'Portuguese Empire', category: 'Iberian Empires', difficulty: 'medium' },
  { civilian: 'Dutch', spy: 'Belgian', category: 'Low Countries', difficulty: 'medium' },
  { civilian: 'Russian Empire', spy: 'Soviet Union', category: 'Russian States', difficulty: 'easy' },
  { civilian: 'Tsarist Russia', spy: 'Imperial Russia', category: 'Russian Periods', difficulty: 'hard' },
  { civilian: 'Mughal India', spy: 'British Raj', category: 'Indian Periods', difficulty: 'medium' },
  { civilian: 'Safavid', spy: 'Qajar', category: 'Persian Dynasties', difficulty: 'hard' },
  { civilian: 'Mamluk', spy: 'Seljuk', category: 'Islamic Empires', difficulty: 'hard' },
  { civilian: 'Abbasid', spy: 'Umayyad', category: 'Arab Caliphates', difficulty: 'hard' },
  { civilian: 'Swahili', spy: 'Zulu', category: 'African Cultures', difficulty: 'hard' },
  { civilian: 'Mali Empire', spy: 'Songhai Empire', category: 'West African', difficulty: 'hard' },
  { civilian: 'Ethiopia', spy: 'Nubia', category: 'Northeast African', difficulty: 'hard' },
  { civilian: 'Polynesian', spy: 'Melanesian', category: 'Pacific Cultures', difficulty: 'hard' },
  { civilian: 'Maori', spy: 'Aboriginal', category: 'Indigenous Oceania', difficulty: 'medium' },
  { civilian: 'Iroquois', spy: 'Cherokee', category: 'Native American', difficulty: 'medium' },
  { civilian: 'Sioux', spy: 'Apache', category: 'Plains Indians', difficulty: 'medium' },
  { civilian: 'Comanche', spy: 'Cheyenne', category: 'Native Americans', difficulty: 'hard' },
  { civilian: 'Inuit', spy: 'Aleut', category: 'Arctic Peoples', difficulty: 'hard' },
  { civilian: 'Hittites', spy: 'Assyrians', category: 'Ancient Near East', difficulty: 'hard' },
  { civilian: 'Sumerians', spy: 'Akkadians', category: 'Mesopotamian', difficulty: 'hard' },
  { civilian: 'Macedonians', spy: 'Thracians', category: 'Balkan Peoples', difficulty: 'hard' },
  { civilian: 'Illyrians', spy: 'Dacians', category: 'Ancient Balkans', difficulty: 'hard' },
  { civilian: 'Scythians', spy: 'Sarmatians', category: 'Steppe Nomads', difficulty: 'hard' },
  { civilian: 'Huns', spy: 'Mongols', category: 'Nomadic Invaders', difficulty: 'medium' },
  { civilian: 'Turks', spy: 'Tatars', category: 'Turkic Peoples', difficulty: 'hard' },
];
