// Entertainment Pack - 300 keywords about movies, TV, games, and pop culture
import { KeywordPair } from '../defaultKeywords';

export const ENTERTAINMENT_PACK_KEYWORDS: KeywordPair[] = [
  // MOVIE GENRES (30 pairs)
  { civilian: 'Action', spy: 'Adventure', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Comedy', spy: 'Romance', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Horror', spy: 'Thriller', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Drama', spy: 'Documentary', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Science Fiction', spy: 'Fantasy', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Western', spy: 'War', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Musical', spy: 'Dance', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Mystery', spy: 'Crime', category: 'Movie Genres', difficulty: 'easy' },
  { civilian: 'Animation', spy: 'Cartoon', category: 'Movie Genres', difficulty: 'hard' },
  { civilian: 'Biography', spy: 'Historical', category: 'Movie Genres', difficulty: 'medium' },
  { civilian: 'Superhero', spy: 'Comic Book', category: 'Movie Genres', difficulty: 'medium' },
  { civilian: 'Zombie', spy: 'Vampire', category: 'Horror Subgenres', difficulty: 'easy' },
  { civilian: 'Werewolf', spy: 'Monster', category: 'Horror Creatures', difficulty: 'easy' },
  { civilian: 'Ghost', spy: 'Spirit', category: 'Supernatural', difficulty: 'hard' },
  { civilian: 'Alien', spy: 'Extraterrestrial', category: 'Sci-Fi', difficulty: 'hard' },
  { civilian: 'Robot', spy: 'Android', category: 'Sci-Fi', difficulty: 'medium' },
  { civilian: 'Cyborg', spy: 'AI', category: 'Sci-Fi', difficulty: 'medium' },
  { civilian: 'Time Travel', spy: 'Parallel Universe', category: 'Sci-Fi Concepts', difficulty: 'medium' },
  { civilian: 'Apocalypse', spy: 'Post-Apocalyptic', category: 'Themes', difficulty: 'medium' },
  { civilian: 'Dystopia', spy: 'Utopia', category: 'Themes', difficulty: 'hard' },
  { civilian: 'Spy', spy: 'Secret Agent', category: 'Characters', difficulty: 'hard' },
  { civilian: 'Detective', spy: 'Investigator', category: 'Characters', difficulty: 'medium' },
  { civilian: 'Hero', spy: 'Villain', category: 'Characters', difficulty: 'easy' },
  { civilian: 'Protagonist', spy: 'Antagonist', category: 'Story Elements', difficulty: 'hard' },
  { civilian: 'Sequel', spy: 'Prequel', category: 'Film Series', difficulty: 'easy' },
  { civilian: 'Remake', spy: 'Reboot', category: 'Film Types', difficulty: 'medium' },
  { civilian: 'Director', spy: 'Producer', category: 'Film Crew', difficulty: 'easy' },
  { civilian: 'Actor', spy: 'Actress', category: 'Film Crew', difficulty: 'easy' },
  { civilian: 'Oscar', spy: 'Emmy', category: 'Awards', difficulty: 'easy' },
  { civilian: 'Golden Globe', spy: 'Grammy', category: 'Awards', difficulty: 'easy' },

  // FAMOUS MOVIES (40 pairs)
  { civilian: 'Star Wars', spy: 'Star Trek', category: 'Sci-Fi Franchises', difficulty: 'easy' },
  { civilian: 'Harry Potter', spy: 'Lord of the Rings', category: 'Fantasy', difficulty: 'easy' },
  { civilian: 'Marvel', spy: 'DC', category: 'Comic Universes', difficulty: 'easy' },
  { civilian: 'Avengers', spy: 'Justice League', category: 'Superhero Teams', difficulty: 'easy' },
  { civilian: 'Iron Man', spy: 'Batman', category: 'Superheroes', difficulty: 'easy' },
  { civilian: 'Superman', spy: 'Captain America', category: 'Superheroes', difficulty: 'easy' },
  { civilian: 'Spider-Man', spy: 'X-Men', category: 'Marvel', difficulty: 'easy' },
  { civilian: 'Hulk', spy: 'Thor', category: 'Marvel Heroes', difficulty: 'easy' },
  { civilian: 'Wonder Woman', spy: 'Black Widow', category: 'Female Heroes', difficulty: 'easy' },
  { civilian: 'Joker', spy: 'Thanos', category: 'Villains', difficulty: 'easy' },
  { civilian: 'Titanic', spy: 'Avatar', category: 'James Cameron', difficulty: 'easy' },
  { civilian: 'Jurassic Park', spy: 'King Kong', category: 'Monster Movies', difficulty: 'easy' },
  { civilian: 'Jaws', spy: 'Godzilla', category: 'Monster Movies', difficulty: 'easy' },
  { civilian: 'E.T.', spy: 'Close Encounters', category: 'Alien Movies', difficulty: 'medium' },
  { civilian: 'Indiana Jones', spy: 'National Treasure', category: 'Adventure', difficulty: 'easy' },
  { civilian: 'Pirates of Caribbean', spy: 'Treasure Island', category: 'Pirate Movies', difficulty: 'easy' },
  { civilian: 'Frozen', spy: 'Tangled', category: 'Disney', difficulty: 'easy' },
  { civilian: 'Lion King', spy: 'Jungle Book', category: 'Disney Classics', difficulty: 'easy' },
  { civilian: 'Toy Story', spy: 'Shrek', category: 'Animation', difficulty: 'easy' },
  { civilian: 'Finding Nemo', spy: 'Finding Dory', category: 'Pixar', difficulty: 'easy' },
  { civilian: 'Up', spy: 'Wall-E', category: 'Pixar', difficulty: 'easy' },
  { civilian: 'Monsters Inc', spy: 'Despicable Me', category: 'Animation', difficulty: 'easy' },
  { civilian: 'Minions', spy: 'Smurfs', category: 'Animated Characters', difficulty: 'easy' },
  { civilian: 'Terminator', spy: 'RoboCop', category: 'Robot Movies', difficulty: 'easy' },
  { civilian: 'Matrix', spy: 'Inception', category: 'Mind-Bending', difficulty: 'easy' },
  { civilian: 'Back to the Future', spy: 'Doctor Who', category: 'Time Travel', difficulty: 'easy' },
  { civilian: 'Fast and Furious', spy: 'Need for Speed', category: 'Car Movies', difficulty: 'easy' },
  { civilian: 'Mission Impossible', spy: 'James Bond', category: 'Spy Movies', difficulty: 'easy' },
  { civilian: 'Rocky', spy: 'Creed', category: 'Boxing Movies', difficulty: 'easy' },
  { civilian: 'Karate Kid', spy: 'Cobra Kai', category: 'Martial Arts', difficulty: 'easy' },
  { civilian: 'Godfather', spy: 'Scarface', category: 'Gangster Movies', difficulty: 'easy' },
  { civilian: 'Forrest Gump', spy: 'Cast Away', category: 'Tom Hanks', difficulty: 'medium' },
  { civilian: 'Gladiator', spy: 'Braveheart', category: 'Historical Epics', difficulty: 'easy' },
  { civilian: 'Silence of Lambs', spy: 'Psycho', category: 'Psychological Thriller', difficulty: 'medium' },
  { civilian: 'Shining', spy: 'The Exorcist', category: 'Horror Classics', difficulty: 'easy' },
  { civilian: 'Scream', spy: 'Nightmare on Elm', category: 'Slasher Films', difficulty: 'easy' },
  { civilian: 'Friday the 13th', spy: 'Halloween', category: 'Slasher Films', difficulty: 'easy' },
  { civilian: 'Saw', spy: 'Hostel', category: 'Horror', difficulty: 'easy' },
  { civilian: 'Conjuring', spy: 'Insidious', category: 'Modern Horror', difficulty: 'medium' },
  { civilian: 'It', spy: 'Stranger Things', category: 'Stephen King', difficulty: 'easy' },

  // TV SHOWS (50 pairs)
  { civilian: 'Game of Thrones', spy: 'Vikings', category: 'Medieval Shows', difficulty: 'easy' },
  { civilian: 'Breaking Bad', spy: 'Better Call Saul', category: 'Crime Drama', difficulty: 'easy' },
  { civilian: 'Friends', spy: 'How I Met Your Mother', category: 'Sitcoms', difficulty: 'easy' },
  { civilian: 'The Office', spy: 'Parks and Recreation', category: 'Workplace Comedy', difficulty: 'easy' },
  { civilian: 'Seinfeld', spy: 'Curb Your Enthusiasm', category: 'Comedy', difficulty: 'medium' },
  { civilian: 'Big Bang Theory', spy: 'Young Sheldon', category: 'Nerd Comedy', difficulty: 'easy' },
  { civilian: 'Stranger Things', spy: 'Dark', category: 'Sci-Fi Mystery', difficulty: 'easy' },
  { civilian: 'Black Mirror', spy: 'Twilight Zone', category: 'Anthology', difficulty: 'medium' },
  { civilian: 'Walking Dead', spy: 'Fear the Walking Dead', category: 'Zombie Shows', difficulty: 'easy' },
  { civilian: 'Westworld', spy: 'Battlestar Galactica', category: 'Sci-Fi', difficulty: 'medium' },
  { civilian: 'Lost', spy: 'The Island', category: 'Mystery', difficulty: 'medium' },
  { civilian: 'Prison Break', spy: 'Escape Plan', category: 'Escape Stories', difficulty: 'easy' },
  { civilian: 'Dexter', spy: 'Hannibal', category: 'Serial Killer Shows', difficulty: 'easy' },
  { civilian: 'Sherlock', spy: 'Elementary', category: 'Detective Shows', difficulty: 'easy' },
  { civilian: 'CSI', spy: 'NCIS', category: 'Crime Investigation', difficulty: 'easy' },
  { civilian: 'Law & Order', spy: 'Criminal Minds', category: 'Police Procedural', difficulty: 'easy' },
  { civilian: 'House', spy: 'Grey\'s Anatomy', category: 'Medical Drama', difficulty: 'easy' },
  { civilian: 'ER', spy: 'Scrubs', category: 'Hospital Shows', difficulty: 'easy' },
  { civilian: 'Suits', spy: 'Boston Legal', category: 'Legal Drama', difficulty: 'medium' },
  { civilian: 'Mad Men', spy: 'The Crown', category: 'Period Drama', difficulty: 'medium' },
  { civilian: 'Downton Abbey', spy: 'Bridgerton', category: 'Period Drama', difficulty: 'medium' },
  { civilian: 'Peaky Blinders', spy: 'Boardwalk Empire', category: 'Gangster Shows', difficulty: 'medium' },
  { civilian: 'Narcos', spy: 'Ozark', category: 'Drug Crime', difficulty: 'easy' },
  { civilian: 'House of Cards', spy: 'Designated Survivor', category: 'Political Thriller', difficulty: 'medium' },
  { civilian: 'The Wire', spy: 'Sopranos', category: 'Crime Drama', difficulty: 'medium' },
  { civilian: 'True Detective', spy: 'Mindhunter', category: 'Crime Thriller', difficulty: 'medium' },
  { civilian: 'Witcher', spy: 'Shadow and Bone', category: 'Fantasy', difficulty: 'medium' },
  { civilian: 'Mandalorian', spy: 'Book of Boba Fett', category: 'Star Wars TV', difficulty: 'easy' },
  { civilian: 'WandaVision', spy: 'Loki', category: 'Marvel TV', difficulty: 'easy' },
  { civilian: 'Arrow', spy: 'The Flash', category: 'DC TV', difficulty: 'easy' },
  { civilian: 'Supergirl', spy: 'Batwoman', category: 'DC Female Heroes', difficulty: 'medium' },
  { civilian: 'Rick and Morty', spy: 'Futurama', category: 'Adult Animation', difficulty: 'easy' },
  { civilian: 'South Park', spy: 'Family Guy', category: 'Adult Cartoon', difficulty: 'easy' },
  { civilian: 'Simpsons', spy: 'Bob\'s Burgers', category: 'Animated Sitcom', difficulty: 'easy' },
  { civilian: 'SpongeBob', spy: 'Paw Patrol', category: 'Kids Shows', difficulty: 'easy' },
  { civilian: 'Pokemon', spy: 'Digimon', category: 'Anime', difficulty: 'easy' },
  { civilian: 'Dragon Ball', spy: 'Naruto', category: 'Anime', difficulty: 'easy' },
  { civilian: 'One Piece', spy: 'Bleach', category: 'Anime', difficulty: 'medium' },
  { civilian: 'Attack on Titan', spy: 'Death Note', category: 'Dark Anime', difficulty: 'medium' },
  { civilian: 'Demon Slayer', spy: 'Jujutsu Kaisen', category: 'Modern Anime', difficulty: 'hard' },
  { civilian: 'MasterChef', spy: 'Top Chef', category: 'Cooking Shows', difficulty: 'easy' },
  { civilian: 'American Idol', spy: 'The Voice', category: 'Singing Shows', difficulty: 'easy' },
  { civilian: 'Survivor', spy: 'Big Brother', category: 'Reality Shows', difficulty: 'easy' },
  { civilian: 'Bachelor', spy: 'Love Island', category: 'Dating Shows', difficulty: 'easy' },
  { civilian: 'America\'s Got Talent', spy: 'Britain\'s Got Talent', category: 'Talent Shows', difficulty: 'easy' },
  { civilian: 'Jeopardy', spy: 'Wheel of Fortune', category: 'Game Shows', difficulty: 'easy' },
  { civilian: 'Who Wants Millionaire', spy: 'Deal or No Deal', category: 'Game Shows', difficulty: 'easy' },
  { civilian: 'Saturday Night Live', spy: 'Mad TV', category: 'Sketch Comedy', difficulty: 'medium' },
  { civilian: 'Tonight Show', spy: 'Late Show', category: 'Late Night', difficulty: 'medium' },
  { civilian: 'Ellen', spy: 'Oprah', category: 'Talk Shows', difficulty: 'easy' },

  // VIDEO GAMES (50 pairs)
  { civilian: 'Mario', spy: 'Sonic', category: 'Platform Games', difficulty: 'easy' },
  { civilian: 'Nintendo', spy: 'PlayStation', category: 'Game Consoles', difficulty: 'easy' },
  { civilian: 'Xbox', spy: 'Switch', category: 'Game Consoles', difficulty: 'easy' },
  { civilian: 'Fortnite', spy: 'PUBG', category: 'Battle Royale', difficulty: 'easy' },
  { civilian: 'Call of Duty', spy: 'Battlefield', category: 'FPS', difficulty: 'easy' },
  { civilian: 'Halo', spy: 'Destiny', category: 'Sci-Fi Shooter', difficulty: 'easy' },
  { civilian: 'Minecraft', spy: 'Roblox', category: 'Sandbox Games', difficulty: 'easy' },
  { civilian: 'Pokemon', spy: 'Zelda', category: 'Nintendo', difficulty: 'easy' },
  { civilian: 'FIFA', spy: 'PES', category: 'Soccer Games', difficulty: 'easy' },
  { civilian: 'NBA 2K', spy: 'NBA Live', category: 'Basketball Games', difficulty: 'easy' },
  { civilian: 'Madden', spy: 'NCAA Football', category: 'Football Games', difficulty: 'easy' },
  { civilian: 'Gran Turismo', spy: 'Forza', category: 'Racing Simulators', difficulty: 'easy' },
  { civilian: 'Mario Kart', spy: 'Crash Team Racing', category: 'Kart Racing', difficulty: 'easy' },
  { civilian: 'GTA', spy: 'Red Dead', category: 'Rockstar Games', difficulty: 'easy' },
  { civilian: 'Assassin\'s Creed', spy: 'Far Cry', category: 'Ubisoft', difficulty: 'easy' },
  { civilian: 'Uncharted', spy: 'Tomb Raider', category: 'Adventure', difficulty: 'easy' },
  { civilian: 'God of War', spy: 'Devil May Cry', category: 'Action', difficulty: 'medium' },
  { civilian: 'The Witcher', spy: 'Skyrim', category: 'RPG', difficulty: 'easy' },
  { civilian: 'Final Fantasy', spy: 'Dragon Quest', category: 'JRPG', difficulty: 'easy' },
  { civilian: 'Dark Souls', spy: 'Bloodborne', category: 'Souls-like', difficulty: 'medium' },
  { civilian: 'Elden Ring', spy: 'Sekiro', category: 'FromSoftware', difficulty: 'medium' },
  { civilian: 'Resident Evil', spy: 'Silent Hill', category: 'Horror Games', difficulty: 'easy' },
  { civilian: 'Dead Space', spy: 'Alien Isolation', category: 'Sci-Fi Horror', difficulty: 'medium' },
  { civilian: 'The Last of Us', spy: 'Days Gone', category: 'Post-Apocalyptic', difficulty: 'easy' },
  { civilian: 'Fallout', spy: 'Metro', category: 'Nuclear Wasteland', difficulty: 'medium' },
  { civilian: 'Overwatch', spy: 'Valorant', category: 'Hero Shooter', difficulty: 'easy' },
  { civilian: 'League of Legends', spy: 'Dota 2', category: 'MOBA', difficulty: 'easy' },
  { civilian: 'Counter-Strike', spy: 'Rainbow Six', category: 'Tactical Shooter', difficulty: 'easy' },
  { civilian: 'Apex Legends', spy: 'Warzone', category: 'Battle Royale', difficulty: 'easy' },
  { civilian: 'Rocket League', spy: 'Smash Bros', category: 'Competitive', difficulty: 'easy' },
  { civilian: 'Street Fighter', spy: 'Mortal Kombat', category: 'Fighting Games', difficulty: 'easy' },
  { civilian: 'Tekken', spy: 'Soul Calibur', category: 'Fighting Games', difficulty: 'medium' },
  { civilian: 'Pac-Man', spy: 'Tetris', category: 'Arcade Classics', difficulty: 'easy' },
  { civilian: 'Space Invaders', spy: 'Galaga', category: 'Retro Shooters', difficulty: 'medium' },
  { civilian: 'Donkey Kong', spy: 'Mega Man', category: 'Classic Platformers', difficulty: 'medium' },
  { civilian: 'Metroid', spy: 'Castlevania', category: 'Metroidvania', difficulty: 'hard' },
  { civilian: 'Kirby', spy: 'Yoshi', category: 'Nintendo Characters', difficulty: 'easy' },
  { civilian: 'Animal Crossing', spy: 'Stardew Valley', category: 'Simulation', difficulty: 'easy' },
  { civilian: 'Sims', spy: 'Second Life', category: 'Life Simulation', difficulty: 'easy' },
  { civilian: 'Civilization', spy: 'Age of Empires', category: 'Strategy', difficulty: 'easy' },
  { civilian: 'StarCraft', spy: 'Warcraft', category: 'RTS', difficulty: 'easy' },
  { civilian: 'World of Warcraft', spy: 'Final Fantasy XIV', category: 'MMORPG', difficulty: 'easy' },
  { civilian: 'Hearthstone', spy: 'Magic the Gathering', category: 'Card Games', difficulty: 'easy' },
  { civilian: 'Among Us', spy: 'Fall Guys', category: 'Party Games', difficulty: 'easy' },
  { civilian: 'Candy Crush', spy: 'Bejeweled', category: 'Mobile Games', difficulty: 'easy' },
  { civilian: 'Angry Birds', spy: 'Cut the Rope', category: 'Mobile Games', difficulty: 'easy' },
  { civilian: 'Clash of Clans', spy: 'Clash Royale', category: 'Mobile Strategy', difficulty: 'easy' },
  { civilian: 'PUBG Mobile', spy: 'Free Fire', category: 'Mobile Battle Royale', difficulty: 'easy' },
  { civilian: 'Genshin Impact', spy: 'Honkai Impact', category: 'Gacha Games', difficulty: 'hard' },
  { civilian: 'VR Chat', spy: 'Rec Room', category: 'VR Social', difficulty: 'medium' },

  // MUSIC & ARTISTS (40 pairs)
  { civilian: 'Beatles', spy: 'Rolling Stones', category: 'Rock Bands', difficulty: 'easy' },
  { civilian: 'Queen', spy: 'Led Zeppelin', category: 'Classic Rock', difficulty: 'easy' },
  { civilian: 'Pink Floyd', spy: 'The Who', category: 'Progressive Rock', difficulty: 'medium' },
  { civilian: 'Elvis', spy: 'Michael Jackson', category: 'Pop Icons', difficulty: 'easy' },
  { civilian: 'Madonna', spy: 'Lady Gaga', category: 'Pop Divas', difficulty: 'easy' },
  { civilian: 'Beyonce', spy: 'Rihanna', category: 'Modern Pop', difficulty: 'easy' },
  { civilian: 'Taylor Swift', spy: 'Ariana Grande', category: 'Pop Stars', difficulty: 'easy' },
  { civilian: 'Adele', spy: 'Sam Smith', category: 'Soul Singers', difficulty: 'easy' },
  { civilian: 'Ed Sheeran', spy: 'Shawn Mendes', category: 'Pop Singers', difficulty: 'easy' },
  { civilian: 'Justin Bieber', spy: 'Harry Styles', category: 'Male Pop', difficulty: 'easy' },
  { civilian: 'Drake', spy: 'Kanye West', category: 'Hip Hop', difficulty: 'easy' },
  { civilian: 'Eminem', spy: '50 Cent', category: 'Rap', difficulty: 'easy' },
  { civilian: 'Jay-Z', spy: 'Nas', category: 'Hip Hop Legends', difficulty: 'medium' },
  { civilian: 'Snoop Dogg', spy: 'Dr. Dre', category: 'West Coast Rap', difficulty: 'easy' },
  { civilian: 'Tupac', spy: 'Biggie', category: 'Rap Legends', difficulty: 'easy' },
  { civilian: 'Kendrick Lamar', spy: 'J. Cole', category: 'Modern Hip Hop', difficulty: 'easy' },
  { civilian: 'Post Malone', spy: 'Travis Scott', category: 'Trap Artists', difficulty: 'easy' },
  { civilian: 'BTS', spy: 'Blackpink', category: 'K-Pop', difficulty: 'easy' },
  { civilian: 'One Direction', spy: 'Backstreet Boys', category: 'Boy Bands', difficulty: 'easy' },
  { civilian: 'NSYNC', spy: 'Boyz II Men', category: '90s Boy Bands', difficulty: 'medium' },
  { civilian: 'Spice Girls', spy: 'Destiny\'s Child', category: 'Girl Groups', difficulty: 'easy' },
  { civilian: 'Metallica', spy: 'Iron Maiden', category: 'Heavy Metal', difficulty: 'easy' },
  { civilian: 'AC/DC', spy: 'Guns N\' Roses', category: 'Hard Rock', difficulty: 'easy' },
  { civilian: 'Nirvana', spy: 'Pearl Jam', category: 'Grunge', difficulty: 'easy' },
  { civilian: 'Green Day', spy: 'Blink-182', category: 'Punk Rock', difficulty: 'easy' },
  { civilian: 'Coldplay', spy: 'U2', category: 'Alternative Rock', difficulty: 'easy' },
  { civilian: 'Imagine Dragons', spy: 'OneRepublic', category: 'Modern Rock', difficulty: 'easy' },
  { civilian: 'Maroon 5', spy: 'Train', category: 'Pop Rock', difficulty: 'easy' },
  { civilian: 'ABBA', spy: 'Bee Gees', category: 'Disco', difficulty: 'easy' },
  { civilian: 'Frank Sinatra', spy: 'Dean Martin', category: 'Jazz', difficulty: 'medium' },
  { civilian: 'Louis Armstrong', spy: 'Ella Fitzgerald', category: 'Jazz Legends', difficulty: 'medium' },
  { civilian: 'Bob Marley', spy: 'Peter Tosh', category: 'Reggae', difficulty: 'medium' },
  { civilian: 'Johnny Cash', spy: 'Willie Nelson', category: 'Country', difficulty: 'easy' },
  { civilian: 'Dolly Parton', spy: 'Shania Twain', category: 'Country Female', difficulty: 'easy' },
  { civilian: 'Garth Brooks', spy: 'Kenny Chesney', category: 'Country Male', difficulty: 'medium' },
  { civilian: 'Daft Punk', spy: 'Calvin Harris', category: 'Electronic', difficulty: 'easy' },
  { civilian: 'Avicii', spy: 'David Guetta', category: 'EDM', difficulty: 'easy' },
  { civilian: 'Marshmello', spy: 'The Chainsmokers', category: 'Modern EDM', difficulty: 'easy' },
  { civilian: 'DJ Khaled', spy: 'Diplo', category: 'DJ Producers', difficulty: 'easy' },
  { civilian: 'Spotify', spy: 'Apple Music', category: 'Streaming', difficulty: 'easy' },

  // SOCIAL MEDIA & INTERNET (40 pairs)
  { civilian: 'Facebook', spy: 'MySpace', category: 'Social Networks', difficulty: 'easy' },
  { civilian: 'Instagram', spy: 'Snapchat', category: 'Photo Apps', difficulty: 'easy' },
  { civilian: 'Twitter', spy: 'Threads', category: 'Microblogging', difficulty: 'easy' },
  { civilian: 'TikTok', spy: 'Vine', category: 'Short Videos', difficulty: 'easy' },
  { civilian: 'YouTube', spy: 'Vimeo', category: 'Video Platforms', difficulty: 'easy' },
  { civilian: 'Twitch', spy: 'YouTube Gaming', category: 'Streaming', difficulty: 'easy' },
  { civilian: 'Reddit', spy: 'Digg', category: 'Forums', difficulty: 'medium' },
  { civilian: 'Discord', spy: 'Slack', category: 'Chat Apps', difficulty: 'easy' },
  { civilian: 'WhatsApp', spy: 'Telegram', category: 'Messaging', difficulty: 'easy' },
  { civilian: 'Messenger', spy: 'WeChat', category: 'Chat Apps', difficulty: 'easy' },
  { civilian: 'LinkedIn', spy: 'Indeed', category: 'Professional', difficulty: 'easy' },
  { civilian: 'Pinterest', spy: 'Tumblr', category: 'Visual Platforms', difficulty: 'easy' },
  { civilian: 'Zoom', spy: 'Skype', category: 'Video Calls', difficulty: 'easy' },
  { civilian: 'Google Meet', spy: 'Microsoft Teams', category: 'Business Video', difficulty: 'easy' },
  { civilian: 'FaceTime', spy: 'Duo', category: 'Video Chat', difficulty: 'easy' },
  { civilian: 'Amazon', spy: 'eBay', category: 'E-commerce', difficulty: 'easy' },
  { civilian: 'Etsy', spy: 'Shopify', category: 'Online Stores', difficulty: 'medium' },
  { civilian: 'PayPal', spy: 'Venmo', category: 'Payment', difficulty: 'easy' },
  { civilian: 'Uber', spy: 'Lyft', category: 'Rideshare', difficulty: 'easy' },
  { civilian: 'Uber Eats', spy: 'DoorDash', category: 'Food Delivery', difficulty: 'easy' },
  { civilian: 'Airbnb', spy: 'VRBO', category: 'Vacation Rental', difficulty: 'easy' },
  { civilian: 'Booking.com', spy: 'Expedia', category: 'Travel Sites', difficulty: 'easy' },
  { civilian: 'Tinder', spy: 'Bumble', category: 'Dating Apps', difficulty: 'easy' },
  { civilian: 'Match', spy: 'eHarmony', category: 'Dating Sites', difficulty: 'medium' },
  { civilian: 'Gmail', spy: 'Outlook', category: 'Email', difficulty: 'easy' },
  { civilian: 'Chrome', spy: 'Firefox', category: 'Browsers', difficulty: 'easy' },
  { civilian: 'Safari', spy: 'Edge', category: 'Browsers', difficulty: 'easy' },
  { civilian: 'iPhone', spy: 'Android', category: 'Smartphones', difficulty: 'easy' },
  { civilian: 'iOS', spy: 'Windows', category: 'Operating Systems', difficulty: 'easy' },
  { civilian: 'Mac', spy: 'PC', category: 'Computers', difficulty: 'easy' },
  { civilian: 'iPad', spy: 'Kindle', category: 'Tablets', difficulty: 'easy' },
  { civilian: 'Apple Watch', spy: 'Fitbit', category: 'Wearables', difficulty: 'easy' },
  { civilian: 'AirPods', spy: 'Galaxy Buds', category: 'Earbuds', difficulty: 'easy' },
  { civilian: 'Alexa', spy: 'Google Home', category: 'Smart Speakers', difficulty: 'easy' },
  { civilian: 'Siri', spy: 'Google Assistant', category: 'Voice Assistants', difficulty: 'easy' },
  { civilian: 'Netflix', spy: 'Hulu', category: 'Streaming TV', difficulty: 'easy' },
  { civilian: 'Disney Plus', spy: 'HBO Max', category: 'Streaming Services', difficulty: 'easy' },
  { civilian: 'Amazon Prime', spy: 'Paramount Plus', category: 'Streaming', difficulty: 'easy' },
  { civilian: 'Podcast', spy: 'Audiobook', category: 'Audio Content', difficulty: 'easy' },
  { civilian: 'Influencer', spy: 'Content Creator', category: 'Internet Personalities', difficulty: 'hard' },
];
