// Science & Education Pack - 200 keywords about science, math, and education
import { KeywordPair } from '../defaultKeywords';

export const SCIENCE_PACK_KEYWORDS: KeywordPair[] = [
  // PHYSICS (30 pairs)
  { civilian: 'Gravity', spy: 'Magnetism', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Energy', spy: 'Force', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Mass', spy: 'Weight', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Velocity', spy: 'Acceleration', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Momentum', spy: 'Inertia', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Atom', spy: 'Molecule', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Proton', spy: 'Electron', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Neutron', spy: 'Photon', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Light', spy: 'Sound', category: 'Physics', difficulty: 'easy' },
  { civilian: 'Wave', spy: 'Particle', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Frequency', spy: 'Wavelength', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Radiation', spy: 'Emission', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Fusion', spy: 'Fission', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Conductor', spy: 'Insulator', category: 'Physics', difficulty: 'easy' },
  { civilian: 'Static', spy: 'Current', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Voltage', spy: 'Amperage', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Circuit', spy: 'Network', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Reflection', spy: 'Refraction', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Lens', spy: 'Mirror', category: 'Physics', difficulty: 'easy' },
  { civilian: 'Convex', spy: 'Concave', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Solid', spy: 'Liquid', category: 'Physics', difficulty: 'easy' },
  { civilian: 'Gas', spy: 'Plasma', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Pressure', spy: 'Tension', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Friction', spy: 'Resistance', category: 'Physics', difficulty: 'medium' },
  { civilian: 'Thermal', spy: 'Kinetic', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Potential', spy: 'Mechanical', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Quantum', spy: 'Classical', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Relativity', spy: 'Quantum Theory', category: 'Physics', difficulty: 'hard' },
  { civilian: 'Telescope', spy: 'Microscope', category: 'Instruments', difficulty: 'easy' },
  { civilian: 'Thermometer', spy: 'Barometer', category: 'Instruments', difficulty: 'medium' },

  // CHEMISTRY (30 pairs)
  { civilian: 'Acid', spy: 'Base', category: 'Chemistry', difficulty: 'easy' },
  { civilian: 'Element', spy: 'Compound', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Metal', spy: 'Nonmetal', category: 'Chemistry', difficulty: 'easy' },
  { civilian: 'Oxidation', spy: 'Reduction', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Catalyst', spy: 'Inhibitor', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Solution', spy: 'Mixture', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Solvent', spy: 'Solute', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Dissolve', spy: 'Precipitate', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Evaporation', spy: 'Condensation', category: 'Chemistry', difficulty: 'easy' },
  { civilian: 'Melting', spy: 'Freezing', category: 'Chemistry', difficulty: 'easy' },
  { civilian: 'Boiling', spy: 'Sublimation', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Organic', spy: 'Inorganic', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Carbon', spy: 'Silicon', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Oxygen', spy: 'Nitrogen', category: 'Chemistry', difficulty: 'easy' },
  { civilian: 'Hydrogen', spy: 'Helium', category: 'Chemistry', difficulty: 'easy' },
  { civilian: 'Sodium', spy: 'Potassium', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Iron', spy: 'Copper', category: 'Chemistry', difficulty: 'easy' },
  { civilian: 'Calcium', spy: 'Magnesium', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Chlorine', spy: 'Fluorine', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Sulfur', spy: 'Phosphorus', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Isotope', spy: 'Ion', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Covalent', spy: 'Ionic', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Exothermic', spy: 'Endothermic', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'pH Scale', spy: 'Litmus Test', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Molecule', spy: 'Formula', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Reaction', spy: 'Equation', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Periodic Table', spy: 'Atomic Number', category: 'Chemistry', difficulty: 'medium' },
  { civilian: 'Alkali', spy: 'Halogen', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Noble Gas', spy: 'Rare Earth', category: 'Chemistry', difficulty: 'hard' },
  { civilian: 'Polymer', spy: 'Monomer', category: 'Chemistry', difficulty: 'hard' },

  // BIOLOGY (30 pairs)
  { civilian: 'Cell', spy: 'Tissue', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Nucleus', spy: 'Cytoplasm', category: 'Biology', difficulty: 'medium' },
  { civilian: 'DNA', spy: 'RNA', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Gene', spy: 'Chromosome', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Mitosis', spy: 'Meiosis', category: 'Biology', difficulty: 'hard' },
  { civilian: 'Photosynthesis', spy: 'Respiration', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Herbivore', spy: 'Carnivore', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Predator', spy: 'Prey', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Producer', spy: 'Consumer', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Ecosystem', spy: 'Biome', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Species', spy: 'Genus', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Vertebrate', spy: 'Invertebrate', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Mammal', spy: 'Reptile', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Amphibian', spy: 'Fish', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Bird', spy: 'Insect', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Bacteria', spy: 'Virus', category: 'Biology', difficulty: 'easy' },
  { civilian: 'Fungus', spy: 'Mold', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Parasite', spy: 'Symbiosis', category: 'Biology', difficulty: 'hard' },
  { civilian: 'Evolution', spy: 'Natural Selection', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Mutation', spy: 'Adaptation', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Genetics', spy: 'Heredity', category: 'Biology', difficulty: 'hard' },
  { civilian: 'Dominant', spy: 'Recessive', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Genotype', spy: 'Phenotype', category: 'Biology', difficulty: 'hard' },
  { civilian: 'Enzyme', spy: 'Protein', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Hormone', spy: 'Antibody', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Immune System', spy: 'Lymphatic System', category: 'Biology', difficulty: 'hard' },
  { civilian: 'Artery', spy: 'Vein', category: 'Biology', difficulty: 'medium' },
  { civilian: 'Neuron', spy: 'Synapse', category: 'Biology', difficulty: 'hard' },
  { civilian: 'Chlorophyll', spy: 'Chloroplast', category: 'Biology', difficulty: 'hard' },
  { civilian: 'Embryo', spy: 'Fetus', category: 'Biology', difficulty: 'medium' },

  // MATHEMATICS (30 pairs)
  { civilian: 'Addition', spy: 'Subtraction', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Multiplication', spy: 'Division', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Sum', spy: 'Difference', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Product', spy: 'Quotient', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Fraction', spy: 'Decimal', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Numerator', spy: 'Denominator', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Percent', spy: 'Ratio', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Even', spy: 'Odd', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Prime', spy: 'Composite', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Integer', spy: 'Whole Number', category: 'Mathematics', difficulty: 'hard' },
  { civilian: 'Positive', spy: 'Negative', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Rational', spy: 'Irrational', category: 'Mathematics', difficulty: 'hard' },
  { civilian: 'Real', spy: 'Imaginary', category: 'Mathematics', difficulty: 'hard' },
  { civilian: 'Variable', spy: 'Constant', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Equation', spy: 'Inequality', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Linear', spy: 'Quadratic', category: 'Mathematics', difficulty: 'hard' },
  { civilian: 'Function', spy: 'Relation', category: 'Mathematics', difficulty: 'hard' },
  { civilian: 'Domain', spy: 'Range', category: 'Mathematics', difficulty: 'hard' },
  { civilian: 'Slope', spy: 'Intercept', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Parallel', spy: 'Perpendicular', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Acute', spy: 'Obtuse', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Right Angle', spy: 'Straight Angle', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Triangle', spy: 'Quadrilateral', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Square', spy: 'Rectangle', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Circle', spy: 'Ellipse', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Radius', spy: 'Diameter', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Circumference', spy: 'Perimeter', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Area', spy: 'Volume', category: 'Mathematics', difficulty: 'easy' },
  { civilian: 'Mean', spy: 'Median', category: 'Mathematics', difficulty: 'medium' },
  { civilian: 'Mode', spy: 'Range', category: 'Mathematics', difficulty: 'medium' },

  // ASTRONOMY (30 pairs)
  { civilian: 'Planet', spy: 'Star', category: 'Astronomy', difficulty: 'easy' },
  { civilian: 'Moon', spy: 'Satellite', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Comet', spy: 'Asteroid', category: 'Astronomy', difficulty: 'easy' },
  { civilian: 'Meteor', spy: 'Meteorite', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Galaxy', spy: 'Nebula', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Solar System', spy: 'Milky Way', category: 'Astronomy', difficulty: 'easy' },
  { civilian: 'Orbit', spy: 'Rotation', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Revolution', spy: 'Axis', category: 'Astronomy', difficulty: 'hard' },
  { civilian: 'Eclipse', spy: 'Transit', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Solar Eclipse', spy: 'Lunar Eclipse', category: 'Astronomy', difficulty: 'easy' },
  { civilian: 'Full Moon', spy: 'New Moon', category: 'Astronomy', difficulty: 'easy' },
  { civilian: 'Waxing', spy: 'Waning', category: 'Astronomy', difficulty: 'hard' },
  { civilian: 'Constellation', spy: 'Zodiac', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Big Dipper', spy: 'Little Dipper', category: 'Astronomy', difficulty: 'easy' },
  { civilian: 'North Star', spy: 'Polaris', category: 'Astronomy', difficulty: 'hard' },
  { civilian: 'Mercury', spy: 'Venus', category: 'Planets', difficulty: 'easy' },
  { civilian: 'Earth', spy: 'Mars', category: 'Planets', difficulty: 'easy' },
  { civilian: 'Jupiter', spy: 'Saturn', category: 'Planets', difficulty: 'easy' },
  { civilian: 'Uranus', spy: 'Neptune', category: 'Planets', difficulty: 'easy' },
  { civilian: 'Pluto', spy: 'Dwarf Planet', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Red Giant', spy: 'White Dwarf', category: 'Stars', difficulty: 'hard' },
  { civilian: 'Supernova', spy: 'Black Hole', category: 'Astronomy', difficulty: 'medium' },
  { civilian: 'Pulsar', spy: 'Quasar', category: 'Astronomy', difficulty: 'hard' },
  { civilian: 'Light Year', spy: 'Parsec', category: 'Astronomy', difficulty: 'hard' },
  { civilian: 'Telescope', spy: 'Observatory', category: 'Astronomy', difficulty: 'easy' },
  { civilian: 'Hubble', spy: 'James Webb', category: 'Space Telescopes', difficulty: 'medium' },
  { civilian: 'NASA', spy: 'SpaceX', category: 'Space Agencies', difficulty: 'easy' },
  { civilian: 'Astronaut', spy: 'Cosmonaut', category: 'Space Explorers', difficulty: 'medium' },
  { civilian: 'Rocket', spy: 'Shuttle', category: 'Spacecraft', difficulty: 'easy' },
  { civilian: 'Space Station', spy: 'Satellite', category: 'Space Technology', difficulty: 'easy' },

  // EARTH SCIENCE (25 pairs)
  { civilian: 'Earthquake', spy: 'Volcano', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Tsunami', spy: 'Hurricane', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Tornado', spy: 'Cyclone', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Thunder', spy: 'Lightning', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Climate', spy: 'Weather', category: 'Earth Science', difficulty: 'medium' },
  { civilian: 'Atmosphere', spy: 'Stratosphere', category: 'Earth Science', difficulty: 'hard' },
  { civilian: 'Lithosphere', spy: 'Hydrosphere', category: 'Earth Science', difficulty: 'hard' },
  { civilian: 'Magma', spy: 'Lava', category: 'Earth Science', difficulty: 'medium' },
  { civilian: 'Igneous', spy: 'Sedimentary', category: 'Rocks', difficulty: 'medium' },
  { civilian: 'Metamorphic', spy: 'Volcanic', category: 'Rocks', difficulty: 'hard' },
  { civilian: 'Mineral', spy: 'Crystal', category: 'Earth Science', difficulty: 'medium' },
  { civilian: 'Erosion', spy: 'Weathering', category: 'Earth Science', difficulty: 'medium' },
  { civilian: 'Glacier', spy: 'Iceberg', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Canyon', spy: 'Valley', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Plateau', spy: 'Plain', category: 'Earth Science', difficulty: 'medium' },
  { civilian: 'Peninsula', spy: 'Island', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Bay', spy: 'Gulf', category: 'Earth Science', difficulty: 'medium' },
  { civilian: 'Lake', spy: 'Pond', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Creek', spy: 'Brook', category: 'Earth Science', difficulty: 'hard' },
  { civilian: 'Delta', spy: 'Estuary', category: 'Earth Science', difficulty: 'hard' },
  { civilian: 'Tide', spy: 'Current', category: 'Earth Science', difficulty: 'medium' },
  { civilian: 'High Tide', spy: 'Low Tide', category: 'Earth Science', difficulty: 'easy' },
  { civilian: 'Crust', spy: 'Mantle', category: 'Earth Layers', difficulty: 'medium' },
  { civilian: 'Core', spy: 'Outer Core', category: 'Earth Layers', difficulty: 'hard' },
  { civilian: 'Continental', spy: 'Oceanic', category: 'Earth Science', difficulty: 'hard' },

  // COMPUTER SCIENCE (25 pairs)
  { civilian: 'Hardware', spy: 'Software', category: 'Computer Science', difficulty: 'easy' },
  { civilian: 'Input', spy: 'Output', category: 'Computer Science', difficulty: 'easy' },
  { civilian: 'RAM', spy: 'ROM', category: 'Computer Science', difficulty: 'medium' },
  { civilian: 'CPU', spy: 'GPU', category: 'Computer Science', difficulty: 'medium' },
  { civilian: 'Byte', spy: 'Bit', category: 'Computer Science', difficulty: 'medium' },
  { civilian: 'Binary', spy: 'Hexadecimal', category: 'Computer Science', difficulty: 'hard' },
  { civilian: 'Algorithm', spy: 'Program', category: 'Computer Science', difficulty: 'medium' },
  { civilian: 'Loop', spy: 'Function', category: 'Programming', difficulty: 'medium' },
  { civilian: 'Variable', spy: 'Array', category: 'Programming', difficulty: 'medium' },
  { civilian: 'String', spy: 'Integer', category: 'Data Types', difficulty: 'medium' },
  { civilian: 'Boolean', spy: 'Float', category: 'Data Types', difficulty: 'hard' },
  { civilian: 'Syntax', spy: 'Semantics', category: 'Programming', difficulty: 'hard' },
  { civilian: 'Compile', spy: 'Execute', category: 'Programming', difficulty: 'hard' },
  { civilian: 'Debug', spy: 'Test', category: 'Programming', difficulty: 'medium' },
  { civilian: 'Frontend', spy: 'Backend', category: 'Web Development', difficulty: 'easy' },
  { civilian: 'Client', spy: 'Server', category: 'Networking', difficulty: 'easy' },
  { civilian: 'Database', spy: 'Spreadsheet', category: 'Data Storage', difficulty: 'easy' },
  { civilian: 'Upload', spy: 'Download', category: 'Internet', difficulty: 'easy' },
  { civilian: 'Browser', spy: 'Search Engine', category: 'Internet', difficulty: 'easy' },
  { civilian: 'HTTP', spy: 'HTTPS', category: 'Protocols', difficulty: 'medium' },
  { civilian: 'URL', spy: 'IP Address', category: 'Internet', difficulty: 'medium' },
  { civilian: 'Encryption', spy: 'Decryption', category: 'Security', difficulty: 'medium' },
  { civilian: 'Virus', spy: 'Malware', category: 'Security', difficulty: 'easy' },
  { civilian: 'Firewall', spy: 'Antivirus', category: 'Security', difficulty: 'easy' },
  { civilian: 'Cloud', spy: 'Local Storage', category: 'Storage', difficulty: 'easy' },
];
