// Localized default keywords — all 100 free keyword pairs with translations
// Each keyword has: en, vi, es, fr, zh
import { LocalizedKeywordPair } from '../defaultKeywords';

export const DEFAULT_KEYWORDS_LOCALIZED: LocalizedKeywordPair[] = [
  // ============================================================
  // FOOD & DRINKS (20 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Apple', spy: 'Pear' },
      vi: { civilian: 'Táo', spy: 'Lê' },
      es: { civilian: 'Manzana', spy: 'Pera' },
      fr: { civilian: 'Pomme', spy: 'Poire' },
      zh: { civilian: '苹果', spy: '梨' },
      de: { civilian: 'Apfel', spy: 'Birne' },
      ja: { civilian: 'リンゴ', spy: '梨' },
      ko: { civilian: '사과', spy: '배' },
      pt: { civilian: 'Maçã', spy: 'Pera' },
      ru: { civilian: 'Яблоко', spy: 'Груша' },
      ar: { civilian: 'تفاح', spy: 'كمثرى' },
      hi: { civilian: 'सेब', spy: 'नाशपाती' },
      th: { civilian: 'แอปเปิ้ล', spy: 'สาลี่' },
      id: { civilian: 'Apel', spy: 'Pir' },
      tr: { civilian: 'Elma', spy: 'Armut' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Coffee', spy: 'Tea' },
      vi: { civilian: 'Cà phê', spy: 'Trà' },
      es: { civilian: 'Café', spy: 'Té' },
      fr: { civilian: 'Café', spy: 'Thé' },
      zh: { civilian: '咖啡', spy: '茶' },
      de: { civilian: 'Kaffee', spy: 'Tee' },
      ja: { civilian: 'コーヒー', spy: 'お茶' },
      ko: { civilian: '커피', spy: '차' },
      pt: { civilian: 'Café', spy: 'Chá' },
      ru: { civilian: 'Кофе', spy: 'Чай' },
      ar: { civilian: 'قهوة', spy: 'شاي' },
      hi: { civilian: 'कॉफ़ी', spy: 'चाय' },
      th: { civilian: 'กาแฟ', spy: 'ชา' },
      id: { civilian: 'Kopi', spy: 'Teh' },
      tr: { civilian: 'Kahve', spy: 'Çay' },
    },
    category: 'Drinks', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Pizza', spy: 'Burger' },
      vi: { civilian: 'Pizza', spy: 'Bánh mì kẹp' },
      es: { civilian: 'Pizza', spy: 'Hamburguesa' },
      fr: { civilian: 'Pizza', spy: 'Hamburger' },
      zh: { civilian: '披萨', spy: '汉堡' },
      de: { civilian: 'Pizza', spy: 'Burger' },
      ja: { civilian: 'ピザ', spy: 'バーガー' },
      ko: { civilian: '피자', spy: '버거' },
      pt: { civilian: 'Pizza', spy: 'Hambúrguer' },
      ru: { civilian: 'Пицца', spy: 'Бургер' },
      ar: { civilian: 'بيتزا', spy: 'برجر' },
      hi: { civilian: 'पिज़्ज़ा', spy: 'बर्गर' },
      th: { civilian: 'พิซซ่า', spy: 'เบอร์เกอร์' },
      id: { civilian: 'Pizza', spy: 'Burger' },
      tr: { civilian: 'Pizza', spy: 'Burger' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Rice', spy: 'Noodles' },
      vi: { civilian: 'Cơm', spy: 'Mì' },
      es: { civilian: 'Arroz', spy: 'Fideos' },
      fr: { civilian: 'Riz', spy: 'Nouilles' },
      zh: { civilian: '米饭', spy: '面条' },
      de: { civilian: 'Reis', spy: 'Nudeln' },
      ja: { civilian: 'ご飯', spy: '麺' },
      ko: { civilian: '밥', spy: '국수' },
      pt: { civilian: 'Arroz', spy: 'Macarrão' },
      ru: { civilian: 'Рис', spy: 'Лапша' },
      ar: { civilian: 'أرز', spy: 'معكرونة' },
      hi: { civilian: 'चावल', spy: 'नूडल्स' },
      th: { civilian: 'ข้าว', spy: 'เส้นก๋วยเตี๋ยว' },
      id: { civilian: 'Nasi', spy: 'Mie' },
      tr: { civilian: 'Pirinç', spy: 'Erişte' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Chocolate', spy: 'Candy' },
      vi: { civilian: 'Sô cô la', spy: 'Kẹo' },
      es: { civilian: 'Chocolate', spy: 'Caramelo' },
      fr: { civilian: 'Chocolat', spy: 'Bonbon' },
      zh: { civilian: '巧克力', spy: '糖果' },
      de: { civilian: 'Schokolade', spy: 'Bonbon' },
      ja: { civilian: 'チョコレート', spy: 'キャンディ' },
      ko: { civilian: '초콜릿', spy: '사탕' },
      pt: { civilian: 'Chocolate', spy: 'Doce' },
      ru: { civilian: 'Шоколад', spy: 'Конфета' },
      ar: { civilian: 'شوكولاتة', spy: 'حلوى' },
      hi: { civilian: 'चॉकलेट', spy: 'कैंडी' },
      th: { civilian: 'ช็อกโกแลต', spy: 'ลูกอม' },
      id: { civilian: 'Cokelat', spy: 'Permen' },
      tr: { civilian: 'Çikolata', spy: 'Şeker' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Bread', spy: 'Toast' },
      vi: { civilian: 'Bánh mì', spy: 'Bánh mì nướng' },
      es: { civilian: 'Pan', spy: 'Tostada' },
      fr: { civilian: 'Pain', spy: 'Toast' },
      zh: { civilian: '面包', spy: '吐司' },
      de: { civilian: 'Brot', spy: 'Toast' },
      ja: { civilian: 'パン', spy: 'トースト' },
      ko: { civilian: '빵', spy: '토스트' },
      pt: { civilian: 'Pão', spy: 'Torrada' },
      ru: { civilian: 'Хлеб', spy: 'Тост' },
      ar: { civilian: 'خبز', spy: 'توست' },
      hi: { civilian: 'रोटी', spy: 'टोस्ट' },
      th: { civilian: 'ขนมปัง', spy: 'ขนมปังปิ้ง' },
      id: { civilian: 'Roti', spy: 'Roti Panggang' },
      tr: { civilian: 'Ekmek', spy: 'Tost' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Milk', spy: 'Yogurt' },
      vi: { civilian: 'Sữa', spy: 'Sữa chua' },
      es: { civilian: 'Leche', spy: 'Yogur' },
      fr: { civilian: 'Lait', spy: 'Yaourt' },
      zh: { civilian: '牛奶', spy: '酸奶' },
      de: { civilian: 'Milch', spy: 'Joghurt' },
      ja: { civilian: '牛乳', spy: 'ヨーグルト' },
      ko: { civilian: '우유', spy: '요거트' },
      pt: { civilian: 'Leite', spy: 'Iogurte' },
      ru: { civilian: 'Молоко', spy: 'Йогурт' },
      ar: { civilian: 'حليب', spy: 'زبادي' },
      hi: { civilian: 'दूध', spy: 'दही' },
      th: { civilian: 'นม', spy: 'โยเกิร์ต' },
      id: { civilian: 'Susu', spy: 'Yogurt' },
      tr: { civilian: 'Süt', spy: 'Yoğurt' },
    },
    category: 'Drinks', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Steak', spy: 'Pork Chop' },
      vi: { civilian: 'Bò bít tết', spy: 'Sườn heo' },
      es: { civilian: 'Bistec', spy: 'Chuleta de cerdo' },
      fr: { civilian: 'Steak', spy: 'Côtelette de porc' },
      zh: { civilian: '牛排', spy: '猪排' },
      de: { civilian: 'Steak', spy: 'Schweinekotelett' },
      ja: { civilian: 'ステーキ', spy: 'ポークチョップ' },
      ko: { civilian: '스테이크', spy: '돼지갈비' },
      pt: { civilian: 'Bife', spy: 'Costeleta' },
      ru: { civilian: 'Стейк', spy: 'Свиная отбивная' },
      ar: { civilian: 'ستيك', spy: 'شريحة لحم خنزير' },
      hi: { civilian: 'स्टेक', spy: 'पोर्क चॉप' },
      th: { civilian: 'สเต็ก', spy: 'หมูทอด' },
      id: { civilian: 'Steak', spy: 'Daging Babi' },
      tr: { civilian: 'Biftek', spy: 'Pirzola' },
    },
    category: 'Food', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Orange Juice', spy: 'Lemonade' },
      vi: { civilian: 'Nước cam', spy: 'Nước chanh' },
      es: { civilian: 'Jugo de naranja', spy: 'Limonada' },
      fr: { civilian: 'Jus d\'orange', spy: 'Limonade' },
      zh: { civilian: '橙汁', spy: '柠檬水' },
      de: { civilian: 'Orangensaft', spy: 'Limonade' },
      ja: { civilian: 'オレンジジュース', spy: 'レモネード' },
      ko: { civilian: '오렌지주스', spy: '레모네이드' },
      pt: { civilian: 'Suco de Laranja', spy: 'Limonada' },
      ru: { civilian: 'Апельсиновый сок', spy: 'Лимонад' },
      ar: { civilian: 'عصير برتقال', spy: 'عصير ليمون' },
      hi: { civilian: 'संतरे का रस', spy: 'नींबू पानी' },
      th: { civilian: 'น้ำส้ม', spy: 'น้ำมะนาว' },
      id: { civilian: 'Jus Jeruk', spy: 'Limun' },
      tr: { civilian: 'Portakal Suyu', spy: 'Limonata' },
    },
    category: 'Drinks', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Sushi', spy: 'Sashimi' },
      vi: { civilian: 'Sushi', spy: 'Sashimi' },
      es: { civilian: 'Sushi', spy: 'Sashimi' },
      fr: { civilian: 'Sushi', spy: 'Sashimi' },
      zh: { civilian: '寿司', spy: '刺身' },
      de: { civilian: 'Sushi', spy: 'Sashimi' },
      ja: { civilian: '寿司', spy: '刺身' },
      ko: { civilian: '초밥', spy: '사시미' },
      pt: { civilian: 'Sushi', spy: 'Sashimi' },
      ru: { civilian: 'Суши', spy: 'Сашими' },
      ar: { civilian: 'سوشي', spy: 'ساشيمي' },
      hi: { civilian: 'सुशी', spy: 'साशिमी' },
      th: { civilian: 'ซูชิ', spy: 'ซาชิมิ' },
      id: { civilian: 'Sushi', spy: 'Sashimi' },
      tr: { civilian: 'Suşi', spy: 'Saşimi' },
    },
    category: 'Food', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Ice Cream', spy: 'Frozen Yogurt' },
      vi: { civilian: 'Kem', spy: 'Sữa chua đông lạnh' },
      es: { civilian: 'Helado', spy: 'Yogur helado' },
      fr: { civilian: 'Glace', spy: 'Yaourt glacé' },
      zh: { civilian: '冰淇淋', spy: '冻酸奶' },
      de: { civilian: 'Eiscreme', spy: 'Frozen Joghurt' },
      ja: { civilian: 'アイスクリーム', spy: 'フローズンヨーグルト' },
      ko: { civilian: '아이스크림', spy: '프로즌요거트' },
      pt: { civilian: 'Sorvete', spy: 'Iogurte Gelado' },
      ru: { civilian: 'Мороженое', spy: 'Замороженный йогурт' },
      ar: { civilian: 'آيس كريم', spy: 'زبادي مجمد' },
      hi: { civilian: 'आइसक्रीम', spy: 'फ्रोजन योगर्ट' },
      th: { civilian: 'ไอศกรีม', spy: 'โฟรเซนโยเกิร์ต' },
      id: { civilian: 'Es Krim', spy: 'Yogurt Beku' },
      tr: { civilian: 'Dondurma', spy: 'Donmuş Yoğurt' },
    },
    category: 'Food', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Soup', spy: 'Stew' },
      vi: { civilian: 'Súp', spy: 'Hầm' },
      es: { civilian: 'Sopa', spy: 'Guiso' },
      fr: { civilian: 'Soupe', spy: 'Ragoût' },
      zh: { civilian: '汤', spy: '炖菜' },
      de: { civilian: 'Suppe', spy: 'Eintopf' },
      ja: { civilian: 'スープ', spy: 'シチュー' },
      ko: { civilian: '수프', spy: '스튜' },
      pt: { civilian: 'Sopa', spy: 'Ensopado' },
      ru: { civilian: 'Суп', spy: 'Тушёное мясо' },
      ar: { civilian: 'حساء', spy: 'يخنة' },
      hi: { civilian: 'सूप', spy: 'स्टू' },
      th: { civilian: 'ซุป', spy: 'สตูว์' },
      id: { civilian: 'Sup', spy: 'Semur' },
      tr: { civilian: 'Çorba', spy: 'Güveç' },
    },
    category: 'Food', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Cookie', spy: 'Biscuit' },
      vi: { civilian: 'Bánh quy', spy: 'Bánh bích quy' },
      es: { civilian: 'Galleta', spy: 'Bizcocho' },
      fr: { civilian: 'Cookie', spy: 'Biscuit' },
      zh: { civilian: '饼干', spy: '曲奇' },
      de: { civilian: 'Keks', spy: 'Biskuit' },
      ja: { civilian: 'クッキー', spy: 'ビスケット' },
      ko: { civilian: '쿠키', spy: '비스킷' },
      pt: { civilian: 'Biscoito', spy: 'Bolacha' },
      ru: { civilian: 'Печенье', spy: 'Бисквит' },
      ar: { civilian: 'كعكة', spy: 'بسكويت' },
      hi: { civilian: 'कुकी', spy: 'बिस्कुट' },
      th: { civilian: 'คุกกี้', spy: 'บิสกิต' },
      id: { civilian: 'Kue Kering', spy: 'Biskuit' },
      tr: { civilian: 'Kurabiye', spy: 'Bisküvi' },
    },
    category: 'Food', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Cake', spy: 'Pie' },
      vi: { civilian: 'Bánh kem', spy: 'Bánh nướng' },
      es: { civilian: 'Pastel', spy: 'Tarta' },
      fr: { civilian: 'Gâteau', spy: 'Tarte' },
      zh: { civilian: '蛋糕', spy: '派' },
      de: { civilian: 'Kuchen', spy: 'Torte' },
      ja: { civilian: 'ケーキ', spy: 'パイ' },
      ko: { civilian: '케이크', spy: '파이' },
      pt: { civilian: 'Bolo', spy: 'Torta' },
      ru: { civilian: 'Торт', spy: 'Пирог' },
      ar: { civilian: 'كيك', spy: 'فطيرة' },
      hi: { civilian: 'केक', spy: 'पाई' },
      th: { civilian: 'เค้ก', spy: 'พาย' },
      id: { civilian: 'Kue', spy: 'Pai' },
      tr: { civilian: 'Pasta', spy: 'Turta' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Wine', spy: 'Beer' },
      vi: { civilian: 'Rượu vang', spy: 'Bia' },
      es: { civilian: 'Vino', spy: 'Cerveza' },
      fr: { civilian: 'Vin', spy: 'Bière' },
      zh: { civilian: '葡萄酒', spy: '啤酒' },
      de: { civilian: 'Wein', spy: 'Bier' },
      ja: { civilian: 'ワイン', spy: 'ビール' },
      ko: { civilian: '와인', spy: '맥주' },
      pt: { civilian: 'Vinho', spy: 'Cerveja' },
      ru: { civilian: 'Вино', spy: 'Пиво' },
      ar: { civilian: 'نبيذ', spy: 'بيرة' },
      hi: { civilian: 'शराब', spy: 'बीयर' },
      th: { civilian: 'ไวน์', spy: 'เบียร์' },
      id: { civilian: 'Anggur', spy: 'Bir' },
      tr: { civilian: 'Şarap', spy: 'Bira' },
    },
    category: 'Drinks', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Donut', spy: 'Muffin' },
      vi: { civilian: 'Bánh rán', spy: 'Bánh nướng xốp' },
      es: { civilian: 'Dona', spy: 'Muffin' },
      fr: { civilian: 'Beignet', spy: 'Muffin' },
      zh: { civilian: '甜甜圈', spy: '松饼' },
      de: { civilian: 'Donut', spy: 'Muffin' },
      ja: { civilian: 'ドーナツ', spy: 'マフィン' },
      ko: { civilian: '도넛', spy: '머핀' },
      pt: { civilian: 'Rosquinha', spy: 'Muffin' },
      ru: { civilian: 'Пончик', spy: 'Маффин' },
      ar: { civilian: 'دونات', spy: 'مافن' },
      hi: { civilian: 'डोनट', spy: 'मफिन' },
      th: { civilian: 'โดนัท', spy: 'มัฟฟิน' },
      id: { civilian: 'Donat', spy: 'Muffin' },
      tr: { civilian: 'Donut', spy: 'Muffin' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Pancake', spy: 'Waffle' },
      vi: { civilian: 'Bánh kếp', spy: 'Bánh waffle' },
      es: { civilian: 'Panqueque', spy: 'Gofre' },
      fr: { civilian: 'Crêpe', spy: 'Gaufre' },
      zh: { civilian: '煎饼', spy: '华夫饼' },
      de: { civilian: 'Pfannkuchen', spy: 'Waffel' },
      ja: { civilian: 'パンケーキ', spy: 'ワッフル' },
      ko: { civilian: '팬케이크', spy: '와플' },
      pt: { civilian: 'Panqueca', spy: 'Waffle' },
      ru: { civilian: 'Блин', spy: 'Вафля' },
      ar: { civilian: 'بان كيك', spy: 'وافل' },
      hi: { civilian: 'पैनकेक', spy: 'वाफ़ल' },
      th: { civilian: 'แพนเค้ก', spy: 'วาฟเฟิล' },
      id: { civilian: 'Panekuk', spy: 'Wafel' },
      tr: { civilian: 'Krep', spy: 'Waffle' },
    },
    category: 'Food', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Honey', spy: 'Syrup' },
      vi: { civilian: 'Mật ong', spy: 'Xi-rô' },
      es: { civilian: 'Miel', spy: 'Jarabe' },
      fr: { civilian: 'Miel', spy: 'Sirop' },
      zh: { civilian: '蜂蜜', spy: '糖浆' },
      de: { civilian: 'Honig', spy: 'Sirup' },
      ja: { civilian: 'ハチミツ', spy: 'シロップ' },
      ko: { civilian: '꿀', spy: '시럽' },
      pt: { civilian: 'Mel', spy: 'Xarope' },
      ru: { civilian: 'Мёд', spy: 'Сироп' },
      ar: { civilian: 'عسل', spy: 'شراب' },
      hi: { civilian: 'शहद', spy: 'सिरप' },
      th: { civilian: 'น้ำผึ้ง', spy: 'น้ำเชื่อม' },
      id: { civilian: 'Madu', spy: 'Sirup' },
      tr: { civilian: 'Bal', spy: 'Şurup' },
    },
    category: 'Food', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Butter', spy: 'Margarine' },
      vi: { civilian: 'Bơ', spy: 'Bơ thực vật' },
      es: { civilian: 'Mantequilla', spy: 'Margarina' },
      fr: { civilian: 'Beurre', spy: 'Margarine' },
      zh: { civilian: '黄油', spy: '人造黄油' },
      de: { civilian: 'Butter', spy: 'Margarine' },
      ja: { civilian: 'バター', spy: 'マーガリン' },
      ko: { civilian: '버터', spy: '마가린' },
      pt: { civilian: 'Manteiga', spy: 'Margarina' },
      ru: { civilian: 'Масло', spy: 'Маргарин' },
      ar: { civilian: 'زبدة', spy: 'سمن نباتي' },
      hi: { civilian: 'मक्खन', spy: 'मार्जरीन' },
      th: { civilian: 'เนย', spy: 'มาร์การีน' },
      id: { civilian: 'Mentega', spy: 'Margarin' },
      tr: { civilian: 'Tereyağı', spy: 'Margarin' },
    },
    category: 'Food', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Popcorn', spy: 'Chips' },
      vi: { civilian: 'Bỏng ngô', spy: 'Khoai tây chiên' },
      es: { civilian: 'Palomitas', spy: 'Papas fritas' },
      fr: { civilian: 'Pop-corn', spy: 'Chips' },
      zh: { civilian: '爆米花', spy: '薯片' },
      de: { civilian: 'Popcorn', spy: 'Chips' },
      ja: { civilian: 'ポップコーン', spy: 'チップス' },
      ko: { civilian: '팝콘', spy: '감자칩' },
      pt: { civilian: 'Pipoca', spy: 'Batata Frita' },
      ru: { civilian: 'Попкорн', spy: 'Чипсы' },
      ar: { civilian: 'فشار', spy: 'شيبس' },
      hi: { civilian: 'पॉपकॉर्न', spy: 'चिप्स' },
      th: { civilian: 'ป๊อปคอร์น', spy: 'มันฝรั่งทอด' },
      id: { civilian: 'Popcorn', spy: 'Keripik' },
      tr: { civilian: 'Patlamış Mısır', spy: 'Cips' },
    },
    category: 'Food', difficulty: 'easy',
  },

  // ============================================================
  // ANIMALS (15 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Dog', spy: 'Wolf' },
      vi: { civilian: 'Chó', spy: 'Sói' },
      es: { civilian: 'Perro', spy: 'Lobo' },
      fr: { civilian: 'Chien', spy: 'Loup' },
      zh: { civilian: '狗', spy: '狼' },
      de: { civilian: 'Hund', spy: 'Wolf' },
      ja: { civilian: '犬', spy: 'オオカミ' },
      ko: { civilian: '개', spy: '늑대' },
      pt: { civilian: 'Cachorro', spy: 'Lobo' },
      ru: { civilian: 'Собака', spy: 'Волк' },
      ar: { civilian: 'كلب', spy: 'ذئب' },
      hi: { civilian: 'कुत्ता', spy: 'भेड़िया' },
      th: { civilian: 'สุนัข', spy: 'หมาป่า' },
      id: { civilian: 'Anjing', spy: 'Serigala' },
      tr: { civilian: 'Köpek', spy: 'Kurt' },
    },
    category: 'Animals', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Cat', spy: 'Tiger' },
      vi: { civilian: 'Mèo', spy: 'Hổ' },
      es: { civilian: 'Gato', spy: 'Tigre' },
      fr: { civilian: 'Chat', spy: 'Tigre' },
      zh: { civilian: '猫', spy: '老虎' },
      de: { civilian: 'Katze', spy: 'Tiger' },
      ja: { civilian: '猫', spy: 'トラ' },
      ko: { civilian: '고양이', spy: '호랑이' },
      pt: { civilian: 'Gato', spy: 'Tigre' },
      ru: { civilian: 'Кошка', spy: 'Тигр' },
      ar: { civilian: 'قطة', spy: 'نمر' },
      hi: { civilian: 'बिल्ली', spy: 'बाघ' },
      th: { civilian: 'แมว', spy: 'เสือ' },
      id: { civilian: 'Kucing', spy: 'Harimau' },
      tr: { civilian: 'Kedi', spy: 'Kaplan' },
    },
    category: 'Animals', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Horse', spy: 'Zebra' },
      vi: { civilian: 'Ngựa', spy: 'Ngựa vằn' },
      es: { civilian: 'Caballo', spy: 'Cebra' },
      fr: { civilian: 'Cheval', spy: 'Zèbre' },
      zh: { civilian: '马', spy: '斑马' },
      de: { civilian: 'Pferd', spy: 'Zebra' },
      ja: { civilian: '馬', spy: 'シマウマ' },
      ko: { civilian: '말', spy: '얼룩말' },
      pt: { civilian: 'Cavalo', spy: 'Zebra' },
      ru: { civilian: 'Лошадь', spy: 'Зебра' },
      ar: { civilian: 'حصان', spy: 'حمار وحشي' },
      hi: { civilian: 'घोड़ा', spy: 'ज़ेबरा' },
      th: { civilian: 'ม้า', spy: 'ม้าลาย' },
      id: { civilian: 'Kuda', spy: 'Zebra' },
      tr: { civilian: 'At', spy: 'Zebra' },
    },
    category: 'Animals', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Butterfly', spy: 'Moth' },
      vi: { civilian: 'Bướm', spy: 'Bướm đêm' },
      es: { civilian: 'Mariposa', spy: 'Polilla' },
      fr: { civilian: 'Papillon', spy: 'Papillon de nuit' },
      zh: { civilian: '蝴蝶', spy: '飞蛾' },
      de: { civilian: 'Schmetterling', spy: 'Motte' },
      ja: { civilian: '蝶', spy: '蛾' },
      ko: { civilian: '나비', spy: '나방' },
      pt: { civilian: 'Borboleta', spy: 'Mariposa' },
      ru: { civilian: 'Бабочка', spy: 'Моль' },
      ar: { civilian: 'فراشة', spy: 'عثة' },
      hi: { civilian: 'तितली', spy: 'पतंगा' },
      th: { civilian: 'ผีเสื้อ', spy: 'มอด' },
      id: { civilian: 'Kupu-kupu', spy: 'Ngengat' },
      tr: { civilian: 'Kelebek', spy: 'Güve' },
    },
    category: 'Animals', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Frog', spy: 'Toad' },
      vi: { civilian: 'Ếch', spy: 'Cóc' },
      es: { civilian: 'Rana', spy: 'Sapo' },
      fr: { civilian: 'Grenouille', spy: 'Crapaud' },
      zh: { civilian: '青蛙', spy: '蟾蜍' },
      de: { civilian: 'Frosch', spy: 'Kröte' },
      ja: { civilian: 'カエル', spy: 'ヒキガエル' },
      ko: { civilian: '개구리', spy: '두꺼비' },
      pt: { civilian: 'Sapo', spy: 'Sapo' },
      ru: { civilian: 'Лягушка', spy: 'Жаба' },
      ar: { civilian: 'ضفدع', spy: 'علجوم' },
      hi: { civilian: 'मेंढक', spy: 'भेक' },
      th: { civilian: 'กบ', spy: 'คางคก' },
      id: { civilian: 'Katak', spy: 'Kodok' },
      tr: { civilian: 'Kurbağa', spy: 'Kara Kurbağa' },
    },
    category: 'Animals', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Turtle', spy: 'Tortoise' },
      vi: { civilian: 'Rùa biển', spy: 'Rùa cạn' },
      es: { civilian: 'Tortuga marina', spy: 'Tortuga terrestre' },
      fr: { civilian: 'Tortue marine', spy: 'Tortue terrestre' },
      zh: { civilian: '海龟', spy: '陆龟' },
      de: { civilian: 'Schildkröte', spy: 'Landschildkröte' },
      ja: { civilian: 'カメ', spy: 'リクガメ' },
      ko: { civilian: '거북이', spy: '육지거북' },
      pt: { civilian: 'Tartaruga', spy: 'Jabuti' },
      ru: { civilian: 'Черепаха', spy: 'Сухопутная черепаха' },
      ar: { civilian: 'سلحفاة', spy: 'سلحفاة برية' },
      hi: { civilian: 'कछुआ', spy: 'कछुआ' },
      th: { civilian: 'เต่า', spy: 'เต่าบก' },
      id: { civilian: 'Kura-kura', spy: 'Kura-kura Darat' },
      tr: { civilian: 'Kaplumbağa', spy: 'Kara Kaplumbağası' },
    },
    category: 'Animals', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Dolphin', spy: 'Shark' },
      vi: { civilian: 'Cá heo', spy: 'Cá mập' },
      es: { civilian: 'Delfín', spy: 'Tiburón' },
      fr: { civilian: 'Dauphin', spy: 'Requin' },
      zh: { civilian: '海豚', spy: '鲨鱼' },
      de: { civilian: 'Delfin', spy: 'Hai' },
      ja: { civilian: 'イルカ', spy: 'サメ' },
      ko: { civilian: '돌고래', spy: '상어' },
      pt: { civilian: 'Golfinho', spy: 'Tubarão' },
      ru: { civilian: 'Дельфин', spy: 'Акула' },
      ar: { civilian: 'دلفين', spy: 'قرش' },
      hi: { civilian: 'डॉल्फिन', spy: 'शार्क' },
      th: { civilian: 'โลมา', spy: 'ฉลาม' },
      id: { civilian: 'Lumba-lumba', spy: 'Hiu' },
      tr: { civilian: 'Yunus', spy: 'Köpek Balığı' },
    },
    category: 'Animals', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Eagle', spy: 'Hawk' },
      vi: { civilian: 'Đại bàng', spy: 'Diều hâu' },
      es: { civilian: 'Águila', spy: 'Halcón' },
      fr: { civilian: 'Aigle', spy: 'Faucon' },
      zh: { civilian: '鹰', spy: '隼' },
      de: { civilian: 'Adler', spy: 'Falke' },
      ja: { civilian: 'ワシ', spy: 'タカ' },
      ko: { civilian: '독수리', spy: '매' },
      pt: { civilian: 'Águia', spy: 'Falcão' },
      ru: { civilian: 'Орёл', spy: 'Ястреб' },
      ar: { civilian: 'نسر', spy: 'صقر' },
      hi: { civilian: 'गरुड़', spy: 'बाज़' },
      th: { civilian: 'นกอินทรี', spy: 'เหยี่ยว' },
      id: { civilian: 'Elang', spy: 'Elang' },
      tr: { civilian: 'Kartal', spy: 'Şahin' },
    },
    category: 'Animals', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Penguin', spy: 'Puffin' },
      vi: { civilian: 'Chim cánh cụt', spy: 'Chim hải âu' },
      es: { civilian: 'Pingüino', spy: 'Frailecillo' },
      fr: { civilian: 'Pingouin', spy: 'Macareux' },
      zh: { civilian: '企鹅', spy: '海鹦' },
      de: { civilian: 'Pinguin', spy: 'Papageitaucher' },
      ja: { civilian: 'ペンギン', spy: 'パフィン' },
      ko: { civilian: '펭귄', spy: '퍼핀' },
      pt: { civilian: 'Pinguim', spy: 'Papagaio-do-mar' },
      ru: { civilian: 'Пингвин', spy: 'Тупик' },
      ar: { civilian: 'بطريق', spy: 'بفن' },
      hi: { civilian: 'पेंगुइन', spy: 'पफिन' },
      th: { civilian: 'เพนกวิน', spy: 'พัฟฟิน' },
      id: { civilian: 'Penguin', spy: 'Puffin' },
      tr: { civilian: 'Penguen', spy: 'Pufin' },
    },
    category: 'Animals', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Lion', spy: 'Cheetah' },
      vi: { civilian: 'Sư tử', spy: 'Báo gêpa' },
      es: { civilian: 'León', spy: 'Guepardo' },
      fr: { civilian: 'Lion', spy: 'Guépard' },
      zh: { civilian: '狮子', spy: '猎豹' },
      de: { civilian: 'Löwe', spy: 'Gepard' },
      ja: { civilian: 'ライオン', spy: 'チーター' },
      ko: { civilian: '사자', spy: '치타' },
      pt: { civilian: 'Leão', spy: 'Guepardo' },
      ru: { civilian: 'Лев', spy: 'Гепард' },
      ar: { civilian: 'أسد', spy: 'فهد' },
      hi: { civilian: 'शेर', spy: 'चीता' },
      th: { civilian: 'สิงโต', spy: 'เสือชีตาห์' },
      id: { civilian: 'Singa', spy: 'Cheetah' },
      tr: { civilian: 'Aslan', spy: 'Çita' },
    },
    category: 'Animals', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Elephant', spy: 'Hippo' },
      vi: { civilian: 'Voi', spy: 'Hà mã' },
      es: { civilian: 'Elefante', spy: 'Hipopótamo' },
      fr: { civilian: 'Éléphant', spy: 'Hippopotame' },
      zh: { civilian: '大象', spy: '河马' },
      de: { civilian: 'Elefant', spy: 'Nilpferd' },
      ja: { civilian: '象', spy: 'カバ' },
      ko: { civilian: '코끼리', spy: '하마' },
      pt: { civilian: 'Elefante', spy: 'Hipopótamo' },
      ru: { civilian: 'Слон', spy: 'Бегемот' },
      ar: { civilian: 'فيل', spy: 'فرس النهر' },
      hi: { civilian: 'हाथी', spy: 'दरियाई घोड़ा' },
      th: { civilian: 'ช้าง', spy: 'ฮิปโป' },
      id: { civilian: 'Gajah', spy: 'Kuda Nil' },
      tr: { civilian: 'Fil', spy: 'Su Aygırı' },
    },
    category: 'Animals', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Rabbit', spy: 'Hare' },
      vi: { civilian: 'Thỏ nhà', spy: 'Thỏ rừng' },
      es: { civilian: 'Conejo', spy: 'Liebre' },
      fr: { civilian: 'Lapin', spy: 'Lièvre' },
      zh: { civilian: '兔子', spy: '野兔' },
      de: { civilian: 'Kaninchen', spy: 'Hase' },
      ja: { civilian: 'ウサギ', spy: '野ウサギ' },
      ko: { civilian: '토끼', spy: '산토끼' },
      pt: { civilian: 'Coelho', spy: 'Lebre' },
      ru: { civilian: 'Кролик', spy: 'Заяц' },
      ar: { civilian: 'أرنب', spy: 'أرنب بري' },
      hi: { civilian: 'खरगोश', spy: 'ख़रगोश' },
      th: { civilian: 'กระต่าย', spy: 'กระต่ายป่า' },
      id: { civilian: 'Kelinci', spy: 'Kelinci Liar' },
      tr: { civilian: 'Tavşan', spy: 'Yaban Tavşanı' },
    },
    category: 'Animals', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Snake', spy: 'Lizard' },
      vi: { civilian: 'Rắn', spy: 'Thằn lằn' },
      es: { civilian: 'Serpiente', spy: 'Lagarto' },
      fr: { civilian: 'Serpent', spy: 'Lézard' },
      zh: { civilian: '蛇', spy: '蜥蜴' },
      de: { civilian: 'Schlange', spy: 'Eidechse' },
      ja: { civilian: 'ヘビ', spy: 'トカゲ' },
      ko: { civilian: '뱀', spy: '도마뱀' },
      pt: { civilian: 'Cobra', spy: 'Lagarto' },
      ru: { civilian: 'Змея', spy: 'Ящерица' },
      ar: { civilian: 'ثعبان', spy: 'سحلية' },
      hi: { civilian: 'साँप', spy: 'छिपकली' },
      th: { civilian: 'งู', spy: 'จิ้งจก' },
      id: { civilian: 'Ular', spy: 'Kadal' },
      tr: { civilian: 'Yılan', spy: 'Kertenkele' },
    },
    category: 'Animals', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Crocodile', spy: 'Alligator' },
      vi: { civilian: 'Cá sấu', spy: 'Cá sấu mõm ngắn' },
      es: { civilian: 'Cocodrilo', spy: 'Caimán' },
      fr: { civilian: 'Crocodile', spy: 'Alligator' },
      zh: { civilian: '鳄鱼', spy: '短吻鳄' },
      de: { civilian: 'Krokodil', spy: 'Alligator' },
      ja: { civilian: 'ワニ', spy: 'アリゲーター' },
      ko: { civilian: '악어', spy: '앨리게이터' },
      pt: { civilian: 'Crocodilo', spy: 'Jacaré' },
      ru: { civilian: 'Крокодил', spy: 'Аллигатор' },
      ar: { civilian: 'تمساح', spy: 'قاطور' },
      hi: { civilian: 'मगरमच्छ', spy: 'एलीगेटर' },
      th: { civilian: 'จระเข้', spy: 'อัลลิเกเตอร์' },
      id: { civilian: 'Buaya', spy: 'Aligator' },
      tr: { civilian: 'Timsah', spy: 'Timsah' },
    },
    category: 'Animals', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Monkey', spy: 'Gorilla' },
      vi: { civilian: 'Khỉ', spy: 'Khỉ đột' },
      es: { civilian: 'Mono', spy: 'Gorila' },
      fr: { civilian: 'Singe', spy: 'Gorille' },
      zh: { civilian: '猴子', spy: '大猩猩' },
      de: { civilian: 'Affe', spy: 'Gorilla' },
      ja: { civilian: 'サル', spy: 'ゴリラ' },
      ko: { civilian: '원숭이', spy: '고릴라' },
      pt: { civilian: 'Macaco', spy: 'Gorila' },
      ru: { civilian: 'Обезьяна', spy: 'Горилла' },
      ar: { civilian: 'قرد', spy: 'غوريلا' },
      hi: { civilian: 'बंदर', spy: 'गोरिल्ला' },
      th: { civilian: 'ลิง', spy: 'กอริลลา' },
      id: { civilian: 'Monyet', spy: 'Gorila' },
      tr: { civilian: 'Maymun', spy: 'Goril' },
    },
    category: 'Animals', difficulty: 'easy',
  },

  // ============================================================
  // TRANSPORTATION (10 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Car', spy: 'Bike' },
      vi: { civilian: 'Ô tô', spy: 'Xe đạp' },
      es: { civilian: 'Coche', spy: 'Bicicleta' },
      fr: { civilian: 'Voiture', spy: 'Vélo' },
      zh: { civilian: '汽车', spy: '自行车' },
      de: { civilian: 'Auto', spy: 'Fahrrad' },
      ja: { civilian: '車', spy: '自転車' },
      ko: { civilian: '자동차', spy: '자전거' },
      pt: { civilian: 'Carro', spy: 'Bicicleta' },
      ru: { civilian: 'Машина', spy: 'Велосипед' },
      ar: { civilian: 'سيارة', spy: 'دراجة' },
      hi: { civilian: 'कार', spy: 'साइकिल' },
      th: { civilian: 'รถยนต์', spy: 'จักรยาน' },
      id: { civilian: 'Mobil', spy: 'Sepeda' },
      tr: { civilian: 'Araba', spy: 'Bisiklet' },
    },
    category: 'Transport', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Train', spy: 'Subway' },
      vi: { civilian: 'Tàu hỏa', spy: 'Tàu điện ngầm' },
      es: { civilian: 'Tren', spy: 'Metro' },
      fr: { civilian: 'Train', spy: 'Métro' },
      zh: { civilian: '火车', spy: '地铁' },
      de: { civilian: 'Zug', spy: 'U-Bahn' },
      ja: { civilian: '電車', spy: '地下鉄' },
      ko: { civilian: '기차', spy: '지하철' },
      pt: { civilian: 'Trem', spy: 'Metrô' },
      ru: { civilian: 'Поезд', spy: 'Метро' },
      ar: { civilian: 'قطار', spy: 'مترو' },
      hi: { civilian: 'ट्रेन', spy: 'मेट्रो' },
      th: { civilian: 'รถไฟ', spy: 'รถไฟใต้ดิน' },
      id: { civilian: 'Kereta', spy: 'MRT' },
      tr: { civilian: 'Tren', spy: 'Metro' },
    },
    category: 'Transport', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Airplane', spy: 'Helicopter' },
      vi: { civilian: 'Máy bay', spy: 'Trực thăng' },
      es: { civilian: 'Avión', spy: 'Helicóptero' },
      fr: { civilian: 'Avion', spy: 'Hélicoptère' },
      zh: { civilian: '飞机', spy: '直升机' },
      de: { civilian: 'Flugzeug', spy: 'Hubschrauber' },
      ja: { civilian: '飛行機', spy: 'ヘリコプター' },
      ko: { civilian: '비행기', spy: '헬리콥터' },
      pt: { civilian: 'Avião', spy: 'Helicóptero' },
      ru: { civilian: 'Самолёт', spy: 'Вертолёт' },
      ar: { civilian: 'طائرة', spy: 'مروحية' },
      hi: { civilian: 'हवाई जहाज़', spy: 'हेलीकॉप्टर' },
      th: { civilian: 'เครื่องบิน', spy: 'เฮลิคอปเตอร์' },
      id: { civilian: 'Pesawat', spy: 'Helikopter' },
      tr: { civilian: 'Uçak', spy: 'Helikopter' },
    },
    category: 'Transport', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Bus', spy: 'Van' },
      vi: { civilian: 'Xe buýt', spy: 'Xe tải nhỏ' },
      es: { civilian: 'Autobús', spy: 'Furgoneta' },
      fr: { civilian: 'Bus', spy: 'Camionnette' },
      zh: { civilian: '公交车', spy: '面包车' },
      de: { civilian: 'Bus', spy: 'Transporter' },
      ja: { civilian: 'バス', spy: 'バン' },
      ko: { civilian: '버스', spy: '밴' },
      pt: { civilian: 'Ônibus', spy: 'Van' },
      ru: { civilian: 'Автобус', spy: 'Фургон' },
      ar: { civilian: 'حافلة', spy: 'شاحنة صغيرة' },
      hi: { civilian: 'बस', spy: 'वैन' },
      th: { civilian: 'รถบัส', spy: 'รถตู้' },
      id: { civilian: 'Bus', spy: 'Van' },
      tr: { civilian: 'Otobüs', spy: 'Minibüs' },
    },
    category: 'Transport', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Boat', spy: 'Ship' },
      vi: { civilian: 'Thuyền', spy: 'Tàu' },
      es: { civilian: 'Bote', spy: 'Barco' },
      fr: { civilian: 'Bateau', spy: 'Navire' },
      zh: { civilian: '船', spy: '轮船' },
      de: { civilian: 'Boot', spy: 'Schiff' },
      ja: { civilian: 'ボート', spy: '船' },
      ko: { civilian: '보트', spy: '배' },
      pt: { civilian: 'Barco', spy: 'Navio' },
      ru: { civilian: 'Лодка', spy: 'Корабль' },
      ar: { civilian: 'قارب', spy: 'سفينة' },
      hi: { civilian: 'नाव', spy: 'जहाज़' },
      th: { civilian: 'เรือ', spy: 'เรือใหญ่' },
      id: { civilian: 'Perahu', spy: 'Kapal' },
      tr: { civilian: 'Tekne', spy: 'Gemi' },
    },
    category: 'Transport', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Motorcycle', spy: 'Scooter' },
      vi: { civilian: 'Xe máy', spy: 'Xe tay ga' },
      es: { civilian: 'Motocicleta', spy: 'Scooter' },
      fr: { civilian: 'Moto', spy: 'Scooter' },
      zh: { civilian: '摩托车', spy: '踏板车' },
      de: { civilian: 'Motorrad', spy: 'Roller' },
      ja: { civilian: 'バイク', spy: 'スクーター' },
      ko: { civilian: '오토바이', spy: '스쿠터' },
      pt: { civilian: 'Motocicleta', spy: 'Scooter' },
      ru: { civilian: 'Мотоцикл', spy: 'Скутер' },
      ar: { civilian: 'دراجة نارية', spy: 'سكوتر' },
      hi: { civilian: 'मोटरसाइकिल', spy: 'स्कूटर' },
      th: { civilian: 'มอเตอร์ไซค์', spy: 'สกูตเตอร์' },
      id: { civilian: 'Motor', spy: 'Skuter' },
      tr: { civilian: 'Motosiklet', spy: 'Scooter' },
    },
    category: 'Transport', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Taxi', spy: 'Uber' },
      vi: { civilian: 'Taxi', spy: 'Xe công nghệ' },
      es: { civilian: 'Taxi', spy: 'Uber' },
      fr: { civilian: 'Taxi', spy: 'VTC' },
      zh: { civilian: '出租车', spy: '网约车' },
      de: { civilian: 'Taxi', spy: 'Uber' },
      ja: { civilian: 'タクシー', spy: 'Uber' },
      ko: { civilian: '택시', spy: '우버' },
      pt: { civilian: 'Táxi', spy: 'Uber' },
      ru: { civilian: 'Такси', spy: 'Uber' },
      ar: { civilian: 'تاكسي', spy: 'أوبر' },
      hi: { civilian: 'टैक्सी', spy: 'उबर' },
      th: { civilian: 'แท็กซี่', spy: 'อูเบอร์' },
      id: { civilian: 'Taksi', spy: 'Uber' },
      tr: { civilian: 'Taksi', spy: 'Uber' },
    },
    category: 'Transport', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Truck', spy: 'Trailer' },
      vi: { civilian: 'Xe tải', spy: 'Xe moóc' },
      es: { civilian: 'Camión', spy: 'Remolque' },
      fr: { civilian: 'Camion', spy: 'Remorque' },
      zh: { civilian: '卡车', spy: '拖车' },
      de: { civilian: 'LKW', spy: 'Anhänger' },
      ja: { civilian: 'トラック', spy: 'トレーラー' },
      ko: { civilian: '트럭', spy: '트레일러' },
      pt: { civilian: 'Caminhão', spy: 'Reboque' },
      ru: { civilian: 'Грузовик', spy: 'Прицеп' },
      ar: { civilian: 'شاحنة', spy: 'مقطورة' },
      hi: { civilian: 'ट्रक', spy: 'ट्रेलर' },
      th: { civilian: 'รถบรรทุก', spy: 'รถพ่วง' },
      id: { civilian: 'Truk', spy: 'Trailer' },
      tr: { civilian: 'Kamyon', spy: 'Römork' },
    },
    category: 'Transport', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Skateboard', spy: 'Roller Skates' },
      vi: { civilian: 'Ván trượt', spy: 'Giày patin' },
      es: { civilian: 'Monopatín', spy: 'Patines' },
      fr: { civilian: 'Skateboard', spy: 'Rollers' },
      zh: { civilian: '滑板', spy: '轮滑鞋' },
      de: { civilian: 'Skateboard', spy: 'Rollschuhe' },
      ja: { civilian: 'スケートボード', spy: 'ローラースケート' },
      ko: { civilian: '스케이트보드', spy: '롤러스케이트' },
      pt: { civilian: 'Skate', spy: 'Patins' },
      ru: { civilian: 'Скейтборд', spy: 'Ролики' },
      ar: { civilian: 'لوح تزلج', spy: 'تزلج بعجلات' },
      hi: { civilian: 'स्केटबोर्ड', spy: 'रोलर स्केट्स' },
      th: { civilian: 'สเก็ตบอร์ด', spy: 'โรลเลอร์สเก็ต' },
      id: { civilian: 'Skateboard', spy: 'Sepatu Roda' },
      tr: { civilian: 'Kaykay', spy: 'Paten' },
    },
    category: 'Transport', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Hot Air Balloon', spy: 'Parachute' },
      vi: { civilian: 'Khinh khí cầu', spy: 'Dù' },
      es: { civilian: 'Globo aerostático', spy: 'Paracaídas' },
      fr: { civilian: 'Montgolfière', spy: 'Parachute' },
      zh: { civilian: '热气球', spy: '降落伞' },
      de: { civilian: 'Heißluftballon', spy: 'Fallschirm' },
      ja: { civilian: '熱気球', spy: 'パラシュート' },
      ko: { civilian: '열기구', spy: '낙하산' },
      pt: { civilian: 'Balão', spy: 'Paraquedas' },
      ru: { civilian: 'Воздушный шар', spy: 'Парашют' },
      ar: { civilian: 'منطاد', spy: 'مظلة' },
      hi: { civilian: 'गर्म हवा का गुब्बारा', spy: 'पैराशूट' },
      th: { civilian: 'บอลลูน', spy: 'ร่มชูชีพ' },
      id: { civilian: 'Balon Udara', spy: 'Parasut' },
      tr: { civilian: 'Sıcak Hava Balonu', spy: 'Paraşüt' },
    },
    category: 'Transport', difficulty: 'hard',
  },

  // ============================================================
  // MUSIC & INSTRUMENTS (10 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Guitar', spy: 'Piano' },
      vi: { civilian: 'Đàn ghi-ta', spy: 'Đàn piano' },
      es: { civilian: 'Guitarra', spy: 'Piano' },
      fr: { civilian: 'Guitare', spy: 'Piano' },
      zh: { civilian: '吉他', spy: '钢琴' },
      de: { civilian: 'Gitarre', spy: 'Klavier' },
      ja: { civilian: 'ギター', spy: 'ピアノ' },
      ko: { civilian: '기타', spy: '피아노' },
      pt: { civilian: 'Guitarra', spy: 'Piano' },
      ru: { civilian: 'Гитара', spy: 'Пианино' },
      ar: { civilian: 'جيتار', spy: 'بيانو' },
      hi: { civilian: 'गिटार', spy: 'पियानो' },
      th: { civilian: 'กีตาร์', spy: 'เปียโน' },
      id: { civilian: 'Gitar', spy: 'Piano' },
      tr: { civilian: 'Gitar', spy: 'Piyano' },
    },
    category: 'Instruments', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Violin', spy: 'Cello' },
      vi: { civilian: 'Vĩ cầm', spy: 'Đại hồ cầm' },
      es: { civilian: 'Violín', spy: 'Violonchelo' },
      fr: { civilian: 'Violon', spy: 'Violoncelle' },
      zh: { civilian: '小提琴', spy: '大提琴' },
      de: { civilian: 'Geige', spy: 'Cello' },
      ja: { civilian: 'バイオリン', spy: 'チェロ' },
      ko: { civilian: '바이올린', spy: '첼로' },
      pt: { civilian: 'Violino', spy: 'Violoncelo' },
      ru: { civilian: 'Скрипка', spy: 'Виолончель' },
      ar: { civilian: 'كمان', spy: 'تشيلو' },
      hi: { civilian: 'वायलिन', spy: 'चेलो' },
      th: { civilian: 'ไวโอลิน', spy: 'เชลโล' },
      id: { civilian: 'Biola', spy: 'Cello' },
      tr: { civilian: 'Keman', spy: 'Çello' },
    },
    category: 'Instruments', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Drum', spy: 'Cymbal' },
      vi: { civilian: 'Trống', spy: 'Chũm chọe' },
      es: { civilian: 'Tambor', spy: 'Platillo' },
      fr: { civilian: 'Tambour', spy: 'Cymbale' },
      zh: { civilian: '鼓', spy: '钹' },
      de: { civilian: 'Trommel', spy: 'Becken' },
      ja: { civilian: 'ドラム', spy: 'シンバル' },
      ko: { civilian: '드럼', spy: '심벌즈' },
      pt: { civilian: 'Tambor', spy: 'Címbalo' },
      ru: { civilian: 'Барабан', spy: 'Тарелка' },
      ar: { civilian: 'طبل', spy: 'صنج' },
      hi: { civilian: 'ढोल', spy: 'झांझ' },
      th: { civilian: 'กลอง', spy: 'ฉาบ' },
      id: { civilian: 'Drum', spy: 'Simbal' },
      tr: { civilian: 'Davul', spy: 'Zil' },
    },
    category: 'Instruments', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Flute', spy: 'Clarinet' },
      vi: { civilian: 'Sáo', spy: 'Kèn clarinet' },
      es: { civilian: 'Flauta', spy: 'Clarinete' },
      fr: { civilian: 'Flûte', spy: 'Clarinette' },
      zh: { civilian: '长笛', spy: '单簧管' },
      de: { civilian: 'Flöte', spy: 'Klarinette' },
      ja: { civilian: 'フルート', spy: 'クラリネット' },
      ko: { civilian: '플루트', spy: '클라리넷' },
      pt: { civilian: 'Flauta', spy: 'Clarinete' },
      ru: { civilian: 'Флейта', spy: 'Кларнет' },
      ar: { civilian: 'ناي', spy: 'كلارينيت' },
      hi: { civilian: 'बांसुरी', spy: 'शहनाई' },
      th: { civilian: 'ฟลูต', spy: 'คลาริเน็ต' },
      id: { civilian: 'Seruling', spy: 'Klarinet' },
      tr: { civilian: 'Flüt', spy: 'Klarnet' },
    },
    category: 'Instruments', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Trumpet', spy: 'Trombone' },
      vi: { civilian: 'Kèn trumpet', spy: 'Kèn trombone' },
      es: { civilian: 'Trompeta', spy: 'Trombón' },
      fr: { civilian: 'Trompette', spy: 'Trombone' },
      zh: { civilian: '小号', spy: '长号' },
      de: { civilian: 'Trompete', spy: 'Posaune' },
      ja: { civilian: 'トランペット', spy: 'トロンボーン' },
      ko: { civilian: '트럼펫', spy: '트롬본' },
      pt: { civilian: 'Trompete', spy: 'Trombone' },
      ru: { civilian: 'Труба', spy: 'Тромбон' },
      ar: { civilian: 'بوق', spy: 'ترومبون' },
      hi: { civilian: 'तुरही', spy: 'ट्रॉम्बोन' },
      th: { civilian: 'ทรัมเป็ต', spy: 'ทรอมโบน' },
      id: { civilian: 'Terompet', spy: 'Trombon' },
      tr: { civilian: 'Trompet', spy: 'Trombon' },
    },
    category: 'Instruments', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Microphone', spy: 'Speaker' },
      vi: { civilian: 'Micro', spy: 'Loa' },
      es: { civilian: 'Micrófono', spy: 'Altavoz' },
      fr: { civilian: 'Microphone', spy: 'Haut-parleur' },
      zh: { civilian: '麦克风', spy: '音响' },
      de: { civilian: 'Mikrofon', spy: 'Lautsprecher' },
      ja: { civilian: 'マイク', spy: 'スピーカー' },
      ko: { civilian: '마이크', spy: '스피커' },
      pt: { civilian: 'Microfone', spy: 'Alto-falante' },
      ru: { civilian: 'Микрофон', spy: 'Колонка' },
      ar: { civilian: 'ميكروفون', spy: 'سماعة' },
      hi: { civilian: 'माइक्रोफ़ोन', spy: 'स्पीकर' },
      th: { civilian: 'ไมโครโฟน', spy: 'ลำโพง' },
      id: { civilian: 'Mikrofon', spy: 'Speaker' },
      tr: { civilian: 'Mikrofon', spy: 'Hoparlör' },
    },
    category: 'Music', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Headphones', spy: 'Earbuds' },
      vi: { civilian: 'Tai nghe chụp', spy: 'Tai nghe nhét' },
      es: { civilian: 'Auriculares', spy: 'Audífonos' },
      fr: { civilian: 'Casque', spy: 'Écouteurs' },
      zh: { civilian: '头戴耳机', spy: '入耳耳机' },
      de: { civilian: 'Kopfhörer', spy: 'Ohrhörer' },
      ja: { civilian: 'ヘッドフォン', spy: 'イヤホン' },
      ko: { civilian: '헤드폰', spy: '이어폰' },
      pt: { civilian: 'Fone de Ouvido', spy: 'Fone Intra' },
      ru: { civilian: 'Наушники', spy: 'Вкладыши' },
      ar: { civilian: 'سماعات', spy: 'سماعات أذن' },
      hi: { civilian: 'हेडफ़ोन', spy: 'ईयरबड' },
      th: { civilian: 'หูฟัง', spy: 'หูฟังเอียร์บัด' },
      id: { civilian: 'Headphone', spy: 'Earbuds' },
      tr: { civilian: 'Kulaklık', spy: 'Kulak İçi' },
    },
    category: 'Music', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'DJ', spy: 'Producer' },
      vi: { civilian: 'DJ', spy: 'Nhà sản xuất' },
      es: { civilian: 'DJ', spy: 'Productor' },
      fr: { civilian: 'DJ', spy: 'Producteur' },
      zh: { civilian: 'DJ', spy: '制作人' },
      de: { civilian: 'DJ', spy: 'Produzent' },
      ja: { civilian: 'DJ', spy: 'プロデューサー' },
      ko: { civilian: 'DJ', spy: '프로듀서' },
      pt: { civilian: 'DJ', spy: 'Produtor' },
      ru: { civilian: 'Диджей', spy: 'Продюсер' },
      ar: { civilian: 'دي جي', spy: 'منتج' },
      hi: { civilian: 'डीजे', spy: 'प्रोड्यूसर' },
      th: { civilian: 'ดีเจ', spy: 'โปรดิวเซอร์' },
      id: { civilian: 'DJ', spy: 'Produser' },
      tr: { civilian: 'DJ', spy: 'Yapımcı' },
    },
    category: 'Music', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Concert', spy: 'Festival' },
      vi: { civilian: 'Hòa nhạc', spy: 'Lễ hội' },
      es: { civilian: 'Concierto', spy: 'Festival' },
      fr: { civilian: 'Concert', spy: 'Festival' },
      zh: { civilian: '演唱会', spy: '音乐节' },
      de: { civilian: 'Konzert', spy: 'Festival' },
      ja: { civilian: 'コンサート', spy: 'フェスティバル' },
      ko: { civilian: '콘서트', spy: '페스티벌' },
      pt: { civilian: 'Show', spy: 'Festival' },
      ru: { civilian: 'Концерт', spy: 'Фестиваль' },
      ar: { civilian: 'حفلة', spy: 'مهرجان' },
      hi: { civilian: 'कॉन्सर्ट', spy: 'फेस्टिवल' },
      th: { civilian: 'คอนเสิร์ต', spy: 'เทศกาล' },
      id: { civilian: 'Konser', spy: 'Festival' },
      tr: { civilian: 'Konser', spy: 'Festival' },
    },
    category: 'Music', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Singer', spy: 'Rapper' },
      vi: { civilian: 'Ca sĩ', spy: 'Rapper' },
      es: { civilian: 'Cantante', spy: 'Rapero' },
      fr: { civilian: 'Chanteur', spy: 'Rappeur' },
      zh: { civilian: '歌手', spy: '说唱歌手' },
      de: { civilian: 'Sänger', spy: 'Rapper' },
      ja: { civilian: '歌手', spy: 'ラッパー' },
      ko: { civilian: '가수', spy: '래퍼' },
      pt: { civilian: 'Cantor', spy: 'Rapper' },
      ru: { civilian: 'Певец', spy: 'Рэпер' },
      ar: { civilian: 'مغني', spy: 'مغني راب' },
      hi: { civilian: 'गायक', spy: 'रैपर' },
      th: { civilian: 'นักร้อง', spy: 'แรปเปอร์' },
      id: { civilian: 'Penyanyi', spy: 'Rapper' },
      tr: { civilian: 'Şarkıcı', spy: 'Rapçi' },
    },
    category: 'Music', difficulty: 'easy',
  },

  // ============================================================
  // SPORTS & GAMES (10 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Soccer', spy: 'Football' },
      vi: { civilian: 'Bóng đá', spy: 'Bóng bầu dục' },
      es: { civilian: 'Fútbol', spy: 'Fútbol americano' },
      fr: { civilian: 'Football', spy: 'Football américain' },
      zh: { civilian: '足球', spy: '橄榄球' },
      de: { civilian: 'Fußball', spy: 'American Football' },
      ja: { civilian: 'サッカー', spy: 'アメフト' },
      ko: { civilian: '축구', spy: '미식축구' },
      pt: { civilian: 'Futebol', spy: 'Futebol Americano' },
      ru: { civilian: 'Футбол', spy: 'Американский футбол' },
      ar: { civilian: 'كرة قدم', spy: 'كرة قدم أمريكية' },
      hi: { civilian: 'फ़ुटबॉल', spy: 'अमेरिकन फ़ुटबॉल' },
      th: { civilian: 'ฟุตบอล', spy: 'อเมริกันฟุตบอล' },
      id: { civilian: 'Sepak Bola', spy: 'Sepak Bola Amerika' },
      tr: { civilian: 'Futbol', spy: 'Amerikan Futbolu' },
    },
    category: 'Sports', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Basketball', spy: 'Volleyball' },
      vi: { civilian: 'Bóng rổ', spy: 'Bóng chuyền' },
      es: { civilian: 'Baloncesto', spy: 'Voleibol' },
      fr: { civilian: 'Basketball', spy: 'Volleyball' },
      zh: { civilian: '篮球', spy: '排球' },
      de: { civilian: 'Basketball', spy: 'Volleyball' },
      ja: { civilian: 'バスケットボール', spy: 'バレーボール' },
      ko: { civilian: '농구', spy: '배구' },
      pt: { civilian: 'Basquete', spy: 'Vôlei' },
      ru: { civilian: 'Баскетбол', spy: 'Волейбол' },
      ar: { civilian: 'كرة سلة', spy: 'كرة طائرة' },
      hi: { civilian: 'बास्केटबॉल', spy: 'वॉलीबॉल' },
      th: { civilian: 'บาสเกตบอล', spy: 'วอลเลย์บอล' },
      id: { civilian: 'Basket', spy: 'Voli' },
      tr: { civilian: 'Basketbol', spy: 'Voleybol' },
    },
    category: 'Sports', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Tennis', spy: 'Badminton' },
      vi: { civilian: 'Quần vợt', spy: 'Cầu lông' },
      es: { civilian: 'Tenis', spy: 'Bádminton' },
      fr: { civilian: 'Tennis', spy: 'Badminton' },
      zh: { civilian: '网球', spy: '羽毛球' },
      de: { civilian: 'Tennis', spy: 'Badminton' },
      ja: { civilian: 'テニス', spy: 'バドミントン' },
      ko: { civilian: '테니스', spy: '배드민턴' },
      pt: { civilian: 'Tênis', spy: 'Badminton' },
      ru: { civilian: 'Теннис', spy: 'Бадминтон' },
      ar: { civilian: 'تنس', spy: 'تنس الريشة' },
      hi: { civilian: 'टेनिस', spy: 'बैडमिंटन' },
      th: { civilian: 'เทนนิส', spy: 'แบดมินตัน' },
      id: { civilian: 'Tenis', spy: 'Bulu Tangkis' },
      tr: { civilian: 'Tenis', spy: 'Badminton' },
    },
    category: 'Sports', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Swimming', spy: 'Diving' },
      vi: { civilian: 'Bơi lội', spy: 'Lặn' },
      es: { civilian: 'Natación', spy: 'Buceo' },
      fr: { civilian: 'Natation', spy: 'Plongée' },
      zh: { civilian: '游泳', spy: '跳水' },
      de: { civilian: 'Schwimmen', spy: 'Tauchen' },
      ja: { civilian: '水泳', spy: 'ダイビング' },
      ko: { civilian: '수영', spy: '다이빙' },
      pt: { civilian: 'Natação', spy: 'Mergulho' },
      ru: { civilian: 'Плавание', spy: 'Дайвинг' },
      ar: { civilian: 'سباحة', spy: 'غوص' },
      hi: { civilian: 'तैराकी', spy: 'डाइविंग' },
      th: { civilian: 'ว่ายน้ำ', spy: 'ดำน้ำ' },
      id: { civilian: 'Berenang', spy: 'Menyelam' },
      tr: { civilian: 'Yüzme', spy: 'Dalış' },
    },
    category: 'Sports', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Boxing', spy: 'Wrestling' },
      vi: { civilian: 'Quyền Anh', spy: 'Đấu vật' },
      es: { civilian: 'Boxeo', spy: 'Lucha libre' },
      fr: { civilian: 'Boxe', spy: 'Lutte' },
      zh: { civilian: '拳击', spy: '摔跤' },
      de: { civilian: 'Boxen', spy: 'Ringen' },
      ja: { civilian: 'ボクシング', spy: 'レスリング' },
      ko: { civilian: '복싱', spy: '레슬링' },
      pt: { civilian: 'Boxe', spy: 'Luta Livre' },
      ru: { civilian: 'Бокс', spy: 'Борьба' },
      ar: { civilian: 'ملاكمة', spy: 'مصارعة' },
      hi: { civilian: 'मुक्केबाज़ी', spy: 'कुश्ती' },
      th: { civilian: 'มวย', spy: 'มวยปล้ำ' },
      id: { civilian: 'Tinju', spy: 'Gulat' },
      tr: { civilian: 'Boks', spy: 'Güreş' },
    },
    category: 'Sports', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Chess', spy: 'Checkers' },
      vi: { civilian: 'Cờ vua', spy: 'Cờ đam' },
      es: { civilian: 'Ajedrez', spy: 'Damas' },
      fr: { civilian: 'Échecs', spy: 'Dames' },
      zh: { civilian: '国际象棋', spy: '跳棋' },
      de: { civilian: 'Schach', spy: 'Dame' },
      ja: { civilian: 'チェス', spy: 'チェッカー' },
      ko: { civilian: '체스', spy: '체커' },
      pt: { civilian: 'Xadrez', spy: 'Damas' },
      ru: { civilian: 'Шахматы', spy: 'Шашки' },
      ar: { civilian: 'شطرنج', spy: 'داما' },
      hi: { civilian: 'शतरंज', spy: 'चेकर्स' },
      th: { civilian: 'หมากรุก', spy: 'หมากฮอส' },
      id: { civilian: 'Catur', spy: 'Dam' },
      tr: { civilian: 'Satranç', spy: 'Dama' },
    },
    category: 'Games', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Poker', spy: 'Blackjack' },
      vi: { civilian: 'Poker', spy: 'Xì dách' },
      es: { civilian: 'Póker', spy: 'Blackjack' },
      fr: { civilian: 'Poker', spy: 'Blackjack' },
      zh: { civilian: '扑克', spy: '二十一点' },
      de: { civilian: 'Poker', spy: 'Blackjack' },
      ja: { civilian: 'ポーカー', spy: 'ブラックジャック' },
      ko: { civilian: '포커', spy: '블랙잭' },
      pt: { civilian: 'Pôquer', spy: 'Vinte-e-um' },
      ru: { civilian: 'Покер', spy: 'Блэкджек' },
      ar: { civilian: 'بوكر', spy: 'بلاك جاك' },
      hi: { civilian: 'पोकर', spy: 'ब्लैकजैक' },
      th: { civilian: 'โป๊กเกอร์', spy: 'แบล็คแจ็ค' },
      id: { civilian: 'Poker', spy: 'Blackjack' },
      tr: { civilian: 'Poker', spy: 'Blackjack' },
    },
    category: 'Games', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Running', spy: 'Jogging' },
      vi: { civilian: 'Chạy bộ', spy: 'Chạy chậm' },
      es: { civilian: 'Correr', spy: 'Trotar' },
      fr: { civilian: 'Course', spy: 'Jogging' },
      zh: { civilian: '跑步', spy: '慢跑' },
      de: { civilian: 'Laufen', spy: 'Joggen' },
      ja: { civilian: 'ランニング', spy: 'ジョギング' },
      ko: { civilian: '달리기', spy: '조깅' },
      pt: { civilian: 'Corrida', spy: 'Cooper' },
      ru: { civilian: 'Бег', spy: 'Бег трусцой' },
      ar: { civilian: 'جري', spy: 'هرولة' },
      hi: { civilian: 'दौड़', spy: 'जॉगिंग' },
      th: { civilian: 'วิ่ง', spy: 'จ๊อกกิ้ง' },
      id: { civilian: 'Lari', spy: 'Joging' },
      tr: { civilian: 'Koşu', spy: 'Jogging' },
    },
    category: 'Sports', difficulty: 'hard',
  },
  {
    translations: {
      en: { civilian: 'Skiing', spy: 'Snowboarding' },
      vi: { civilian: 'Trượt tuyết', spy: 'Lướt ván tuyết' },
      es: { civilian: 'Esquí', spy: 'Snowboard' },
      fr: { civilian: 'Ski', spy: 'Snowboard' },
      zh: { civilian: '滑雪', spy: '单板滑雪' },
      de: { civilian: 'Skifahren', spy: 'Snowboarden' },
      ja: { civilian: 'スキー', spy: 'スノーボード' },
      ko: { civilian: '스키', spy: '스노보드' },
      pt: { civilian: 'Esqui', spy: 'Snowboard' },
      ru: { civilian: 'Лыжи', spy: 'Сноуборд' },
      ar: { civilian: 'تزلج', spy: 'تزلج على الثلج' },
      hi: { civilian: 'स्कीइंग', spy: 'स्नोबोर्डिंग' },
      th: { civilian: 'สกี', spy: 'สโนว์บอร์ด' },
      id: { civilian: 'Ski', spy: 'Snowboard' },
      tr: { civilian: 'Kayak', spy: 'Snowboard' },
    },
    category: 'Sports', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Golf', spy: 'Mini Golf' },
      vi: { civilian: 'Golf', spy: 'Golf mini' },
      es: { civilian: 'Golf', spy: 'Mini Golf' },
      fr: { civilian: 'Golf', spy: 'Mini Golf' },
      zh: { civilian: '高尔夫', spy: '迷你高尔夫' },
      de: { civilian: 'Golf', spy: 'Minigolf' },
      ja: { civilian: 'ゴルフ', spy: 'ミニゴルフ' },
      ko: { civilian: '골프', spy: '미니골프' },
      pt: { civilian: 'Golfe', spy: 'Minigolfe' },
      ru: { civilian: 'Гольф', spy: 'Мини-гольф' },
      ar: { civilian: 'جولف', spy: 'جولف مصغر' },
      hi: { civilian: 'गोल्फ़', spy: 'मिनी गोल्फ़' },
      th: { civilian: 'กอล์ฟ', spy: 'มินิกอล์ฟ' },
      id: { civilian: 'Golf', spy: 'Mini Golf' },
      tr: { civilian: 'Golf', spy: 'Mini Golf' },
    },
    category: 'Sports', difficulty: 'easy',
  },

  // ============================================================
  // TECHNOLOGY (10 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Phone', spy: 'Tablet' },
      vi: { civilian: 'Điện thoại', spy: 'Máy tính bảng' },
      es: { civilian: 'Teléfono', spy: 'Tableta' },
      fr: { civilian: 'Téléphone', spy: 'Tablette' },
      zh: { civilian: '手机', spy: '平板电脑' },
      de: { civilian: 'Telefon', spy: 'Tablet' },
      ja: { civilian: '電話', spy: 'タブレット' },
      ko: { civilian: '전화', spy: '태블릿' },
      pt: { civilian: 'Telefone', spy: 'Tablet' },
      ru: { civilian: 'Телефон', spy: 'Планшет' },
      ar: { civilian: 'هاتف', spy: 'جهاز لوحي' },
      hi: { civilian: 'फ़ोन', spy: 'टैबलेट' },
      th: { civilian: 'โทรศัพท์', spy: 'แท็บเล็ต' },
      id: { civilian: 'Telepon', spy: 'Tablet' },
      tr: { civilian: 'Telefon', spy: 'Tablet' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Laptop', spy: 'Desktop' },
      vi: { civilian: 'Máy tính xách tay', spy: 'Máy tính bàn' },
      es: { civilian: 'Portátil', spy: 'Ordenador de escritorio' },
      fr: { civilian: 'Ordinateur portable', spy: 'Ordinateur de bureau' },
      zh: { civilian: '笔记本电脑', spy: '台式电脑' },
      de: { civilian: 'Laptop', spy: 'Desktop' },
      ja: { civilian: 'ノートPC', spy: 'デスクトップ' },
      ko: { civilian: '노트북', spy: '데스크톱' },
      pt: { civilian: 'Notebook', spy: 'Desktop' },
      ru: { civilian: 'Ноутбук', spy: 'Десктоп' },
      ar: { civilian: 'حاسوب محمول', spy: 'حاسوب مكتبي' },
      hi: { civilian: 'लैपटॉप', spy: 'डेस्कटॉप' },
      th: { civilian: 'แล็ปท็อป', spy: 'เดสก์ท็อป' },
      id: { civilian: 'Laptop', spy: 'Komputer' },
      tr: { civilian: 'Laptop', spy: 'Masaüstü' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Keyboard', spy: 'Mouse' },
      vi: { civilian: 'Bàn phím', spy: 'Chuột' },
      es: { civilian: 'Teclado', spy: 'Ratón' },
      fr: { civilian: 'Clavier', spy: 'Souris' },
      zh: { civilian: '键盘', spy: '鼠标' },
      de: { civilian: 'Tastatur', spy: 'Maus' },
      ja: { civilian: 'キーボード', spy: 'マウス' },
      ko: { civilian: '키보드', spy: '마우스' },
      pt: { civilian: 'Teclado', spy: 'Mouse' },
      ru: { civilian: 'Клавиатура', spy: 'Мышь' },
      ar: { civilian: 'لوحة مفاتيح', spy: 'فأرة' },
      hi: { civilian: 'कीबोर्ड', spy: 'माउस' },
      th: { civilian: 'คีย์บอร์ด', spy: 'เมาส์' },
      id: { civilian: 'Keyboard', spy: 'Mouse' },
      tr: { civilian: 'Klavye', spy: 'Fare' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'TV', spy: 'Monitor' },
      vi: { civilian: 'Tivi', spy: 'Màn hình' },
      es: { civilian: 'Televisión', spy: 'Monitor' },
      fr: { civilian: 'Télévision', spy: 'Moniteur' },
      zh: { civilian: '电视', spy: '显示器' },
      de: { civilian: 'Fernseher', spy: 'Monitor' },
      ja: { civilian: 'テレビ', spy: 'モニター' },
      ko: { civilian: 'TV', spy: '모니터' },
      pt: { civilian: 'TV', spy: 'Monitor' },
      ru: { civilian: 'Телевизор', spy: 'Монитор' },
      ar: { civilian: 'تلفزيون', spy: 'شاشة' },
      hi: { civilian: 'टीवी', spy: 'मॉनिटर' },
      th: { civilian: 'ทีวี', spy: 'จอมอนิเตอร์' },
      id: { civilian: 'TV', spy: 'Monitor' },
      tr: { civilian: 'TV', spy: 'Monitör' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Camera', spy: 'Webcam' },
      vi: { civilian: 'Máy ảnh', spy: 'Webcam' },
      es: { civilian: 'Cámara', spy: 'Webcam' },
      fr: { civilian: 'Caméra', spy: 'Webcam' },
      zh: { civilian: '相机', spy: '网络摄像头' },
      de: { civilian: 'Kamera', spy: 'Webcam' },
      ja: { civilian: 'カメラ', spy: 'ウェブカメラ' },
      ko: { civilian: '카메라', spy: '웹캠' },
      pt: { civilian: 'Câmera', spy: 'Webcam' },
      ru: { civilian: 'Камера', spy: 'Веб-камера' },
      ar: { civilian: 'كاميرا', spy: 'كاميرا ويب' },
      hi: { civilian: 'कैमरा', spy: 'वेबकैम' },
      th: { civilian: 'กล้อง', spy: 'เว็บแคม' },
      id: { civilian: 'Kamera', spy: 'Webcam' },
      tr: { civilian: 'Kamera', spy: 'Web Kamera' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Facebook', spy: 'Instagram' },
      vi: { civilian: 'Facebook', spy: 'Instagram' },
      es: { civilian: 'Facebook', spy: 'Instagram' },
      fr: { civilian: 'Facebook', spy: 'Instagram' },
      zh: { civilian: 'Facebook', spy: 'Instagram' },
      de: { civilian: 'Facebook', spy: 'Instagram' },
      ja: { civilian: 'Facebook', spy: 'Instagram' },
      ko: { civilian: 'Facebook', spy: 'Instagram' },
      pt: { civilian: 'Facebook', spy: 'Instagram' },
      ru: { civilian: 'Facebook', spy: 'Instagram' },
      ar: { civilian: 'فيسبوك', spy: 'إنستغرام' },
      hi: { civilian: 'फ़ेसबुक', spy: 'इंस्टाग्राम' },
      th: { civilian: 'Facebook', spy: 'Instagram' },
      id: { civilian: 'Facebook', spy: 'Instagram' },
      tr: { civilian: 'Facebook', spy: 'Instagram' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'YouTube', spy: 'TikTok' },
      vi: { civilian: 'YouTube', spy: 'TikTok' },
      es: { civilian: 'YouTube', spy: 'TikTok' },
      fr: { civilian: 'YouTube', spy: 'TikTok' },
      zh: { civilian: 'YouTube', spy: 'TikTok' },
      de: { civilian: 'YouTube', spy: 'TikTok' },
      ja: { civilian: 'YouTube', spy: 'TikTok' },
      ko: { civilian: 'YouTube', spy: 'TikTok' },
      pt: { civilian: 'YouTube', spy: 'TikTok' },
      ru: { civilian: 'YouTube', spy: 'TikTok' },
      ar: { civilian: 'يوتيوب', spy: 'تيك توك' },
      hi: { civilian: 'यूट्यूब', spy: 'टिकटॉक' },
      th: { civilian: 'YouTube', spy: 'TikTok' },
      id: { civilian: 'YouTube', spy: 'TikTok' },
      tr: { civilian: 'YouTube', spy: 'TikTok' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Google', spy: 'Bing' },
      vi: { civilian: 'Google', spy: 'Bing' },
      es: { civilian: 'Google', spy: 'Bing' },
      fr: { civilian: 'Google', spy: 'Bing' },
      zh: { civilian: 'Google', spy: 'Bing' },
      de: { civilian: 'Google', spy: 'Bing' },
      ja: { civilian: 'Google', spy: 'Bing' },
      ko: { civilian: 'Google', spy: 'Bing' },
      pt: { civilian: 'Google', spy: 'Bing' },
      ru: { civilian: 'Google', spy: 'Bing' },
      ar: { civilian: 'جوجل', spy: 'بينج' },
      hi: { civilian: 'गूगल', spy: 'बिंग' },
      th: { civilian: 'Google', spy: 'Bing' },
      id: { civilian: 'Google', spy: 'Bing' },
      tr: { civilian: 'Google', spy: 'Bing' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Email', spy: 'Text Message' },
      vi: { civilian: 'Email', spy: 'Tin nhắn' },
      es: { civilian: 'Correo electrónico', spy: 'Mensaje de texto' },
      fr: { civilian: 'E-mail', spy: 'SMS' },
      zh: { civilian: '电子邮件', spy: '短信' },
      de: { civilian: 'E-Mail', spy: 'SMS' },
      ja: { civilian: 'メール', spy: 'テキスト' },
      ko: { civilian: '이메일', spy: '문자' },
      pt: { civilian: 'E-mail', spy: 'SMS' },
      ru: { civilian: 'Электронная почта', spy: 'СМС' },
      ar: { civilian: 'بريد إلكتروني', spy: 'رسالة نصية' },
      hi: { civilian: 'ईमेल', spy: 'मैसेज' },
      th: { civilian: 'อีเมล', spy: 'ข้อความ' },
      id: { civilian: 'Email', spy: 'SMS' },
      tr: { civilian: 'E-posta', spy: 'Mesaj' },
    },
    category: 'Technology', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'WiFi', spy: 'Bluetooth' },
      vi: { civilian: 'WiFi', spy: 'Bluetooth' },
      es: { civilian: 'WiFi', spy: 'Bluetooth' },
      fr: { civilian: 'WiFi', spy: 'Bluetooth' },
      zh: { civilian: 'WiFi', spy: '蓝牙' },
      de: { civilian: 'WLAN', spy: 'Bluetooth' },
      ja: { civilian: 'Wi-Fi', spy: 'Bluetooth' },
      ko: { civilian: '와이파이', spy: '블루투스' },
      pt: { civilian: 'Wi-Fi', spy: 'Bluetooth' },
      ru: { civilian: 'Wi-Fi', spy: 'Bluetooth' },
      ar: { civilian: 'واي فاي', spy: 'بلوتوث' },
      hi: { civilian: 'वाईफ़ाई', spy: 'ब्लूटूथ' },
      th: { civilian: 'Wi-Fi', spy: 'Bluetooth' },
      id: { civilian: 'WiFi', spy: 'Bluetooth' },
      tr: { civilian: 'WiFi', spy: 'Bluetooth' },
    },
    category: 'Technology', difficulty: 'medium',
  },

  // ============================================================
  // NATURE & WEATHER (10 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Rain', spy: 'Snow' },
      vi: { civilian: 'Mưa', spy: 'Tuyết' },
      es: { civilian: 'Lluvia', spy: 'Nieve' },
      fr: { civilian: 'Pluie', spy: 'Neige' },
      zh: { civilian: '雨', spy: '雪' },
      de: { civilian: 'Regen', spy: 'Schnee' },
      ja: { civilian: '雨', spy: '雪' },
      ko: { civilian: '비', spy: '눈' },
      pt: { civilian: 'Chuva', spy: 'Neve' },
      ru: { civilian: 'Дождь', spy: 'Снег' },
      ar: { civilian: 'مطر', spy: 'ثلج' },
      hi: { civilian: 'बारिश', spy: 'बर्फ़' },
      th: { civilian: 'ฝน', spy: 'หิมะ' },
      id: { civilian: 'Hujan', spy: 'Salju' },
      tr: { civilian: 'Yağmur', spy: 'Kar' },
    },
    category: 'Weather', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Sun', spy: 'Moon' },
      vi: { civilian: 'Mặt trời', spy: 'Mặt trăng' },
      es: { civilian: 'Sol', spy: 'Luna' },
      fr: { civilian: 'Soleil', spy: 'Lune' },
      zh: { civilian: '太阳', spy: '月亮' },
      de: { civilian: 'Sonne', spy: 'Mond' },
      ja: { civilian: '太陽', spy: '月' },
      ko: { civilian: '태양', spy: '달' },
      pt: { civilian: 'Sol', spy: 'Lua' },
      ru: { civilian: 'Солнце', spy: 'Луна' },
      ar: { civilian: 'شمس', spy: 'قمر' },
      hi: { civilian: 'सूरज', spy: 'चाँद' },
      th: { civilian: 'ดวงอาทิตย์', spy: 'ดวงจันทร์' },
      id: { civilian: 'Matahari', spy: 'Bulan' },
      tr: { civilian: 'Güneş', spy: 'Ay' },
    },
    category: 'Nature', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Mountain', spy: 'Hill' },
      vi: { civilian: 'Núi', spy: 'Đồi' },
      es: { civilian: 'Montaña', spy: 'Colina' },
      fr: { civilian: 'Montagne', spy: 'Colline' },
      zh: { civilian: '山', spy: '丘陵' },
      de: { civilian: 'Berg', spy: 'Hügel' },
      ja: { civilian: '山', spy: '丘' },
      ko: { civilian: '산', spy: '언덕' },
      pt: { civilian: 'Montanha', spy: 'Colina' },
      ru: { civilian: 'Гора', spy: 'Холм' },
      ar: { civilian: 'جبل', spy: 'تل' },
      hi: { civilian: 'पहाड़', spy: 'पहाड़ी' },
      th: { civilian: 'ภูเขา', spy: 'เนินเขา' },
      id: { civilian: 'Gunung', spy: 'Bukit' },
      tr: { civilian: 'Dağ', spy: 'Tepe' },
    },
    category: 'Nature', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Ocean', spy: 'Sea' },
      vi: { civilian: 'Đại dương', spy: 'Biển' },
      es: { civilian: 'Océano', spy: 'Mar' },
      fr: { civilian: 'Océan', spy: 'Mer' },
      zh: { civilian: '海洋', spy: '海' },
      de: { civilian: 'Ozean', spy: 'Meer' },
      ja: { civilian: '海', spy: '海' },
      ko: { civilian: '대양', spy: '바다' },
      pt: { civilian: 'Oceano', spy: 'Mar' },
      ru: { civilian: 'Океан', spy: 'Море' },
      ar: { civilian: 'محيط', spy: 'بحر' },
      hi: { civilian: 'महासागर', spy: 'समुद्र' },
      th: { civilian: 'มหาสมุทร', spy: 'ทะเล' },
      id: { civilian: 'Samudra', spy: 'Laut' },
      tr: { civilian: 'Okyanus', spy: 'Deniz' },
    },
    category: 'Nature', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'River', spy: 'Stream' },
      vi: { civilian: 'Sông', spy: 'Suối' },
      es: { civilian: 'Río', spy: 'Arroyo' },
      fr: { civilian: 'Rivière', spy: 'Ruisseau' },
      zh: { civilian: '河流', spy: '小溪' },
      de: { civilian: 'Fluss', spy: 'Bach' },
      ja: { civilian: '川', spy: '小川' },
      ko: { civilian: '강', spy: '시내' },
      pt: { civilian: 'Rio', spy: 'Córrego' },
      ru: { civilian: 'Река', spy: 'Ручей' },
      ar: { civilian: 'نهر', spy: 'جدول' },
      hi: { civilian: 'नदी', spy: 'धारा' },
      th: { civilian: 'แม่น้ำ', spy: 'ลำธาร' },
      id: { civilian: 'Sungai', spy: 'Sungai Kecil' },
      tr: { civilian: 'Nehir', spy: 'Dere' },
    },
    category: 'Nature', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Forest', spy: 'Jungle' },
      vi: { civilian: 'Rừng', spy: 'Rừng nhiệt đới' },
      es: { civilian: 'Bosque', spy: 'Selva' },
      fr: { civilian: 'Forêt', spy: 'Jungle' },
      zh: { civilian: '森林', spy: '丛林' },
      de: { civilian: 'Wald', spy: 'Dschungel' },
      ja: { civilian: '森', spy: 'ジャングル' },
      ko: { civilian: '숲', spy: '정글' },
      pt: { civilian: 'Floresta', spy: 'Selva' },
      ru: { civilian: 'Лес', spy: 'Джунгли' },
      ar: { civilian: 'غابة', spy: 'أدغال' },
      hi: { civilian: 'जंगल', spy: 'जंगल' },
      th: { civilian: 'ป่า', spy: 'ป่าดงดิบ' },
      id: { civilian: 'Hutan', spy: 'Rimba' },
      tr: { civilian: 'Orman', spy: 'Orman' },
    },
    category: 'Nature', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Cloud', spy: 'Fog' },
      vi: { civilian: 'Mây', spy: 'Sương mù' },
      es: { civilian: 'Nube', spy: 'Niebla' },
      fr: { civilian: 'Nuage', spy: 'Brouillard' },
      zh: { civilian: '云', spy: '雾' },
      de: { civilian: 'Wolke', spy: 'Nebel' },
      ja: { civilian: '雲', spy: '霧' },
      ko: { civilian: '구름', spy: '안개' },
      pt: { civilian: 'Nuvem', spy: 'Neblina' },
      ru: { civilian: 'Облако', spy: 'Туман' },
      ar: { civilian: 'سحابة', spy: 'ضباب' },
      hi: { civilian: 'बादल', spy: 'कोहरा' },
      th: { civilian: 'เมฆ', spy: 'หมอก' },
      id: { civilian: 'Awan', spy: 'Kabut' },
      tr: { civilian: 'Bulut', spy: 'Sis' },
    },
    category: 'Weather', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Thunder', spy: 'Lightning' },
      vi: { civilian: 'Sấm', spy: 'Sét' },
      es: { civilian: 'Trueno', spy: 'Relámpago' },
      fr: { civilian: 'Tonnerre', spy: 'Éclair' },
      zh: { civilian: '雷', spy: '闪电' },
      de: { civilian: 'Donner', spy: 'Blitz' },
      ja: { civilian: '雷', spy: '稲妻' },
      ko: { civilian: '천둥', spy: '번개' },
      pt: { civilian: 'Trovão', spy: 'Relâmpago' },
      ru: { civilian: 'Гром', spy: 'Молния' },
      ar: { civilian: 'رعد', spy: 'برق' },
      hi: { civilian: 'गरज', spy: 'बिजली' },
      th: { civilian: 'ฟ้าร้อง', spy: 'ฟ้าแลบ' },
      id: { civilian: 'Guntur', spy: 'Petir' },
      tr: { civilian: 'Gök Gürültüsü', spy: 'Şimşek' },
    },
    category: 'Weather', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Flower', spy: 'Plant' },
      vi: { civilian: 'Hoa', spy: 'Cây' },
      es: { civilian: 'Flor', spy: 'Planta' },
      fr: { civilian: 'Fleur', spy: 'Plante' },
      zh: { civilian: '花', spy: '植物' },
      de: { civilian: 'Blume', spy: 'Pflanze' },
      ja: { civilian: '花', spy: '植物' },
      ko: { civilian: '꽃', spy: '식물' },
      pt: { civilian: 'Flor', spy: 'Planta' },
      ru: { civilian: 'Цветок', spy: 'Растение' },
      ar: { civilian: 'زهرة', spy: 'نبات' },
      hi: { civilian: 'फूल', spy: 'पौधा' },
      th: { civilian: 'ดอกไม้', spy: 'พืช' },
      id: { civilian: 'Bunga', spy: 'Tanaman' },
      tr: { civilian: 'Çiçek', spy: 'Bitki' },
    },
    category: 'Nature', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Tree', spy: 'Bush' },
      vi: { civilian: 'Cây', spy: 'Bụi cây' },
      es: { civilian: 'Árbol', spy: 'Arbusto' },
      fr: { civilian: 'Arbre', spy: 'Buisson' },
      zh: { civilian: '树', spy: '灌木' },
      de: { civilian: 'Baum', spy: 'Busch' },
      ja: { civilian: '木', spy: '茂み' },
      ko: { civilian: '나무', spy: '덤불' },
      pt: { civilian: 'Árvore', spy: 'Arbusto' },
      ru: { civilian: 'Дерево', spy: 'Куст' },
      ar: { civilian: 'شجرة', spy: 'شجيرة' },
      hi: { civilian: 'पेड़', spy: 'झाड़ी' },
      th: { civilian: 'ต้นไม้', spy: 'พุ่มไม้' },
      id: { civilian: 'Pohon', spy: 'Semak' },
      tr: { civilian: 'Ağaç', spy: 'Çalı' },
    },
    category: 'Nature', difficulty: 'easy',
  },

  // ============================================================
  // HOUSEHOLD & OBJECTS (15 pairs)
  // ============================================================
  {
    translations: {
      en: { civilian: 'Bed', spy: 'Couch' },
      vi: { civilian: 'Giường', spy: 'Ghế sofa' },
      es: { civilian: 'Cama', spy: 'Sofá' },
      fr: { civilian: 'Lit', spy: 'Canapé' },
      zh: { civilian: '床', spy: '沙发' },
      de: { civilian: 'Bett', spy: 'Sofa' },
      ja: { civilian: 'ベッド', spy: 'ソファ' },
      ko: { civilian: '침대', spy: '소파' },
      pt: { civilian: 'Cama', spy: 'Sofá' },
      ru: { civilian: 'Кровать', spy: 'Диван' },
      ar: { civilian: 'سرير', spy: 'أريكة' },
      hi: { civilian: 'बिस्तर', spy: 'सोफ़ा' },
      th: { civilian: 'เตียง', spy: 'โซฟา' },
      id: { civilian: 'Tempat Tidur', spy: 'Sofa' },
      tr: { civilian: 'Yatak', spy: 'Kanepe' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Chair', spy: 'Stool' },
      vi: { civilian: 'Ghế', spy: 'Ghế đẩu' },
      es: { civilian: 'Silla', spy: 'Taburete' },
      fr: { civilian: 'Chaise', spy: 'Tabouret' },
      zh: { civilian: '椅子', spy: '凳子' },
      de: { civilian: 'Stuhl', spy: 'Hocker' },
      ja: { civilian: '椅子', spy: 'スツール' },
      ko: { civilian: '의자', spy: '스툴' },
      pt: { civilian: 'Cadeira', spy: 'Banqueta' },
      ru: { civilian: 'Стул', spy: 'Табурет' },
      ar: { civilian: 'كرسي', spy: 'مقعد' },
      hi: { civilian: 'कुर्सी', spy: 'स्टूल' },
      th: { civilian: 'เก้าอี้', spy: 'เก้าอี้สตูล' },
      id: { civilian: 'Kursi', spy: 'Bangku' },
      tr: { civilian: 'Sandalye', spy: 'Tabure' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Table', spy: 'Desk' },
      vi: { civilian: 'Bàn ăn', spy: 'Bàn làm việc' },
      es: { civilian: 'Mesa', spy: 'Escritorio' },
      fr: { civilian: 'Table', spy: 'Bureau' },
      zh: { civilian: '桌子', spy: '书桌' },
      de: { civilian: 'Tisch', spy: 'Schreibtisch' },
      ja: { civilian: 'テーブル', spy: 'デスク' },
      ko: { civilian: '테이블', spy: '책상' },
      pt: { civilian: 'Mesa', spy: 'Escrivaninha' },
      ru: { civilian: 'Стол', spy: 'Письменный стол' },
      ar: { civilian: 'طاولة', spy: 'مكتب' },
      hi: { civilian: 'मेज़', spy: 'डेस्क' },
      th: { civilian: 'โต๊ะ', spy: 'โต๊ะทำงาน' },
      id: { civilian: 'Meja', spy: 'Meja Kerja' },
      tr: { civilian: 'Masa', spy: 'Çalışma Masası' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Lamp', spy: 'Candle' },
      vi: { civilian: 'Đèn', spy: 'Nến' },
      es: { civilian: 'Lámpara', spy: 'Vela' },
      fr: { civilian: 'Lampe', spy: 'Bougie' },
      zh: { civilian: '台灯', spy: '蜡烛' },
      de: { civilian: 'Lampe', spy: 'Kerze' },
      ja: { civilian: 'ランプ', spy: 'ろうそく' },
      ko: { civilian: '램프', spy: '초' },
      pt: { civilian: 'Lâmpada', spy: 'Vela' },
      ru: { civilian: 'Лампа', spy: 'Свеча' },
      ar: { civilian: 'مصباح', spy: 'شمعة' },
      hi: { civilian: 'लैंप', spy: 'मोमबत्ती' },
      th: { civilian: 'โคมไฟ', spy: 'เทียน' },
      id: { civilian: 'Lampu', spy: 'Lilin' },
      tr: { civilian: 'Lamba', spy: 'Mum' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Mirror', spy: 'Window' },
      vi: { civilian: 'Gương', spy: 'Cửa sổ' },
      es: { civilian: 'Espejo', spy: 'Ventana' },
      fr: { civilian: 'Miroir', spy: 'Fenêtre' },
      zh: { civilian: '镜子', spy: '窗户' },
      de: { civilian: 'Spiegel', spy: 'Fenster' },
      ja: { civilian: '鏡', spy: '窓' },
      ko: { civilian: '거울', spy: '창문' },
      pt: { civilian: 'Espelho', spy: 'Janela' },
      ru: { civilian: 'Зеркало', spy: 'Окно' },
      ar: { civilian: 'مرآة', spy: 'نافذة' },
      hi: { civilian: 'दर्पण', spy: 'खिड़की' },
      th: { civilian: 'กระจก', spy: 'หน้าต่าง' },
      id: { civilian: 'Cermin', spy: 'Jendela' },
      tr: { civilian: 'Ayna', spy: 'Pencere' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Door', spy: 'Gate' },
      vi: { civilian: 'Cửa', spy: 'Cổng' },
      es: { civilian: 'Puerta', spy: 'Portón' },
      fr: { civilian: 'Porte', spy: 'Portail' },
      zh: { civilian: '门', spy: '大门' },
      de: { civilian: 'Tür', spy: 'Tor' },
      ja: { civilian: 'ドア', spy: '門' },
      ko: { civilian: '문', spy: '대문' },
      pt: { civilian: 'Porta', spy: 'Portão' },
      ru: { civilian: 'Дверь', spy: 'Ворота' },
      ar: { civilian: 'باب', spy: 'بوابة' },
      hi: { civilian: 'दरवाज़ा', spy: 'गेट' },
      th: { civilian: 'ประตู', spy: 'ประตูรั้ว' },
      id: { civilian: 'Pintu', spy: 'Gerbang' },
      tr: { civilian: 'Kapı', spy: 'Kapı' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Refrigerator', spy: 'Freezer' },
      vi: { civilian: 'Tủ lạnh', spy: 'Tủ đông' },
      es: { civilian: 'Refrigerador', spy: 'Congelador' },
      fr: { civilian: 'Réfrigérateur', spy: 'Congélateur' },
      zh: { civilian: '冰箱', spy: '冷冻柜' },
      de: { civilian: 'Kühlschrank', spy: 'Gefrierschrank' },
      ja: { civilian: '冷蔵庫', spy: '冷凍庫' },
      ko: { civilian: '냉장고', spy: '냉동고' },
      pt: { civilian: 'Geladeira', spy: 'Freezer' },
      ru: { civilian: 'Холодильник', spy: 'Морозильник' },
      ar: { civilian: 'ثلاجة', spy: 'فريزر' },
      hi: { civilian: 'फ्रिज', spy: 'फ्रीज़र' },
      th: { civilian: 'ตู้เย็น', spy: 'ช่องแช่แข็ง' },
      id: { civilian: 'Kulkas', spy: 'Freezer' },
      tr: { civilian: 'Buzdolabı', spy: 'Dondurucu' },
    },
    category: 'Household', difficulty: 'medium',
  },
  {
    translations: {
      en: { civilian: 'Oven', spy: 'Microwave' },
      vi: { civilian: 'Lò nướng', spy: 'Lò vi sóng' },
      es: { civilian: 'Horno', spy: 'Microondas' },
      fr: { civilian: 'Four', spy: 'Micro-ondes' },
      zh: { civilian: '烤箱', spy: '微波炉' },
      de: { civilian: 'Ofen', spy: 'Mikrowelle' },
      ja: { civilian: 'オーブン', spy: '電子レンジ' },
      ko: { civilian: '오븐', spy: '전자레인지' },
      pt: { civilian: 'Forno', spy: 'Micro-ondas' },
      ru: { civilian: 'Духовка', spy: 'Микроволновка' },
      ar: { civilian: 'فرن', spy: 'ميكروويف' },
      hi: { civilian: 'ओवन', spy: 'माइक्रोवेव' },
      th: { civilian: 'เตาอบ', spy: 'ไมโครเวฟ' },
      id: { civilian: 'Oven', spy: 'Microwave' },
      tr: { civilian: 'Fırın', spy: 'Mikrodalga' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Washing Machine', spy: 'Dryer' },
      vi: { civilian: 'Máy giặt', spy: 'Máy sấy' },
      es: { civilian: 'Lavadora', spy: 'Secadora' },
      fr: { civilian: 'Machine à laver', spy: 'Sèche-linge' },
      zh: { civilian: '洗衣机', spy: '烘干机' },
      de: { civilian: 'Waschmaschine', spy: 'Trockner' },
      ja: { civilian: '洗濯機', spy: '乾燥機' },
      ko: { civilian: '세탁기', spy: '건조기' },
      pt: { civilian: 'Máquina de Lavar', spy: 'Secadora' },
      ru: { civilian: 'Стиральная машина', spy: 'Сушилка' },
      ar: { civilian: 'غسالة', spy: 'مجفف' },
      hi: { civilian: 'वॉशिंग मशीन', spy: 'ड्रायर' },
      th: { civilian: 'เครื่องซักผ้า', spy: 'เครื่องอบผ้า' },
      id: { civilian: 'Mesin Cuci', spy: 'Pengering' },
      tr: { civilian: 'Çamaşır Makinesi', spy: 'Kurutma Makinesi' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Fan', spy: 'Air Conditioner' },
      vi: { civilian: 'Quạt', spy: 'Máy lạnh' },
      es: { civilian: 'Ventilador', spy: 'Aire acondicionado' },
      fr: { civilian: 'Ventilateur', spy: 'Climatiseur' },
      zh: { civilian: '风扇', spy: '空调' },
      de: { civilian: 'Ventilator', spy: 'Klimaanlage' },
      ja: { civilian: '扇風機', spy: 'エアコン' },
      ko: { civilian: '선풍기', spy: '에어컨' },
      pt: { civilian: 'Ventilador', spy: 'Ar-condicionado' },
      ru: { civilian: 'Вентилятор', spy: 'Кондиционер' },
      ar: { civilian: 'مروحة', spy: 'مكيف' },
      hi: { civilian: 'पंखा', spy: 'एयर कंडीशनर' },
      th: { civilian: 'พัดลม', spy: 'เครื่องปรับอากาศ' },
      id: { civilian: 'Kipas', spy: 'AC' },
      tr: { civilian: 'Vantilatör', spy: 'Klima' },
    },
    category: 'Household', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Clock', spy: 'Watch' },
      vi: { civilian: 'Đồng hồ treo tường', spy: 'Đồng hồ đeo tay' },
      es: { civilian: 'Reloj de pared', spy: 'Reloj de pulsera' },
      fr: { civilian: 'Horloge', spy: 'Montre' },
      zh: { civilian: '时钟', spy: '手表' },
      de: { civilian: 'Uhr', spy: 'Armbanduhr' },
      ja: { civilian: '時計', spy: '腕時計' },
      ko: { civilian: '시계', spy: '손목시계' },
      pt: { civilian: 'Relógio', spy: 'Relógio de Pulso' },
      ru: { civilian: 'Часы', spy: 'Наручные часы' },
      ar: { civilian: 'ساعة', spy: 'ساعة يد' },
      hi: { civilian: 'घड़ी', spy: 'कलाई घड़ी' },
      th: { civilian: 'นาฬิกา', spy: 'นาฬิกาข้อมือ' },
      id: { civilian: 'Jam', spy: 'Jam Tangan' },
      tr: { civilian: 'Saat', spy: 'Kol Saati' },
    },
    category: 'Objects', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Book', spy: 'Magazine' },
      vi: { civilian: 'Sách', spy: 'Tạp chí' },
      es: { civilian: 'Libro', spy: 'Revista' },
      fr: { civilian: 'Livre', spy: 'Magazine' },
      zh: { civilian: '书', spy: '杂志' },
      de: { civilian: 'Buch', spy: 'Zeitschrift' },
      ja: { civilian: '本', spy: '雑誌' },
      ko: { civilian: '책', spy: '잡지' },
      pt: { civilian: 'Livro', spy: 'Revista' },
      ru: { civilian: 'Книга', spy: 'Журнал' },
      ar: { civilian: 'كتاب', spy: 'مجلة' },
      hi: { civilian: 'किताब', spy: 'पत्रिका' },
      th: { civilian: 'หนังสือ', spy: 'นิตยสาร' },
      id: { civilian: 'Buku', spy: 'Majalah' },
      tr: { civilian: 'Kitap', spy: 'Dergi' },
    },
    category: 'Objects', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Pen', spy: 'Pencil' },
      vi: { civilian: 'Bút bi', spy: 'Bút chì' },
      es: { civilian: 'Bolígrafo', spy: 'Lápiz' },
      fr: { civilian: 'Stylo', spy: 'Crayon' },
      zh: { civilian: '钢笔', spy: '铅笔' },
      de: { civilian: 'Kugelschreiber', spy: 'Bleistift' },
      ja: { civilian: 'ペン', spy: '鉛筆' },
      ko: { civilian: '펜', spy: '연필' },
      pt: { civilian: 'Caneta', spy: 'Lápis' },
      ru: { civilian: 'Ручка', spy: 'Карандаш' },
      ar: { civilian: 'قلم', spy: 'قلم رصاص' },
      hi: { civilian: 'कलम', spy: 'पेंसिल' },
      th: { civilian: 'ปากกา', spy: 'ดินสอ' },
      id: { civilian: 'Pulpen', spy: 'Pensil' },
      tr: { civilian: 'Kalem', spy: 'Kurşun Kalem' },
    },
    category: 'Objects', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Bag', spy: 'Backpack' },
      vi: { civilian: 'Túi xách', spy: 'Ba lô' },
      es: { civilian: 'Bolsa', spy: 'Mochila' },
      fr: { civilian: 'Sac', spy: 'Sac à dos' },
      zh: { civilian: '包', spy: '背包' },
      de: { civilian: 'Tasche', spy: 'Rucksack' },
      ja: { civilian: 'バッグ', spy: 'リュック' },
      ko: { civilian: '가방', spy: '배낭' },
      pt: { civilian: 'Bolsa', spy: 'Mochila' },
      ru: { civilian: 'Сумка', spy: 'Рюкзак' },
      ar: { civilian: 'حقيبة', spy: 'حقيبة ظهر' },
      hi: { civilian: 'बैग', spy: 'बैकपैक' },
      th: { civilian: 'กระเป๋า', spy: 'กระเป๋าเป้' },
      id: { civilian: 'Tas', spy: 'Ransel' },
      tr: { civilian: 'Çanta', spy: 'Sırt Çantası' },
    },
    category: 'Objects', difficulty: 'easy',
  },
  {
    translations: {
      en: { civilian: 'Umbrella', spy: 'Raincoat' },
      vi: { civilian: 'Ô', spy: 'Áo mưa' },
      es: { civilian: 'Paraguas', spy: 'Impermeable' },
      fr: { civilian: 'Parapluie', spy: 'Imperméable' },
      zh: { civilian: '雨伞', spy: '雨衣' },
      de: { civilian: 'Regenschirm', spy: 'Regenmantel' },
      ja: { civilian: '傘', spy: 'レインコート' },
      ko: { civilian: '우산', spy: '우비' },
      pt: { civilian: 'Guarda-chuva', spy: 'Capa de Chuva' },
      ru: { civilian: 'Зонт', spy: 'Дождевик' },
      ar: { civilian: 'مظلة', spy: 'معطف مطر' },
      hi: { civilian: 'छाता', spy: 'बरसाती' },
      th: { civilian: 'ร่ม', spy: 'เสื้อกันฝน' },
      id: { civilian: 'Payung', spy: 'Jas Hujan' },
      tr: { civilian: 'Şemsiye', spy: 'Yağmurluk' },
    },
    category: 'Objects', difficulty: 'easy',
  },
];
